Repository featbit/featbit, pull requests merged in 2022-09, with the labels that each got.

#7 ✨ feat(front-end/persis-lang): persist the current language
  modules/front-end/Dockerfile
  modules/front-end/README.md
  modules/front-end/angular.json
  modules/front-end/karma.conf.js
  modules/front-end/package-lock.json
  modules/front-end/src/app/app.module.ts
  modules/front-end/src/app/shared/locale-switcher/locale-switcher.component.html
  modules/front-end/src/app/shared/locale-switcher/locale-switcher.component.ts
  modules/front-end/src/app/shared/shared.module.ts
  modules/front-end/src/app/shared/utils/localstorage-keys.ts
Labels: UI

#8 ✨ Improve the UI docker process
  modules/front-end/.dockerignore
  modules/front-end/Dockerfile
  modules/front-end/package.json
Labels: UI

#9 ✨Implement the login module
  modules/front-end/README.md
  modules/front-end/package.json
  modules/front-end/src/app/app.component.html
  modules/front-end/src/app/app.module.ts
  modules/front-end/src/app/features/login/do-login/do-login.component.html
  modules/front-end/src/app/features/login/do-login/do-login.component.ts
  modules/front-end/src/app/features/login/login.component.html
  modules/front-end/src/app/features/login/login.component.less
  modules/front-end/src/app/features/login/login.module.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#12 🐛 Fixed the issue when trailing slash is not present after the language code
  modules/front-end/nginx.conf
  modules/front-end/package.json
  modules/front-end/src/app/shared/locale-switcher/locale-switcher.component.ts
Labels: UI

#15 ✨feat(ui/i18n): added locale switcher for logged in pages
  modules/front-end/src/app/core/components/locale-switcher/locale-switcher.component.ts
  modules/front-end/src/app/core/components/menu/menu.component.html
  modules/front-end/src/app/core/components/menu/menu.component.ts
  modules/front-end/src/app/features/safe/experiments/experiments-routing.module.ts
  modules/front-end/src/app/features/safe/segments/details/details-routing.module.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#18 🐛Removed the second close button on modal
  modules/front-end/src/styles.less
Labels: UI

#19 🐛 Fixed mal positioned close button on target user
  modules/front-end/src/app/core/components/target-user-v2/target-user-v2.component.less
Labels: bug, UI

#20 ✨Added api url as build parameter for docker
  modules/front-end/Dockerfile
  modules/front-end/README.md
  modules/front-end/src/environments/environment.prod.ts
  modules/front-end/src/environments/environment.ts
Labels: UI

#21 🧹 Some Refactor On Streaming
  modules/evaluation-server/src/Api/Middlewares/StreamingMiddleware.cs
  modules/evaluation-server/src/Domain/Core/Token.cs
  modules/evaluation-server/src/Domain/Core/TokenNumber.cs
  modules/evaluation-server/src/Domain/WebSockets/Connection.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionStore.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionType.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionVersion.cs
  modules/evaluation-server/src/Domain/WebSockets/RequestHandler.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ConnectionTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/StreamingTestApp.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ValidationTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/Core/TokenNumberTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/Core/TokenTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionStoreTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionTypeTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/RequestHandlerTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/VersionTests.cs
Labels: Evaluation Server

#22 ✨ Translate menu
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.html
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.less
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.ts
  modules/front-end/src/app/core/components/find-rule/targeted-user-table/targeted-user-table.component.ts
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/menu/menu.component.html
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/features/safe/safe.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#24 ✨ WebSocket Handler Implementation
  modules/evaluation-server/EvaluationServer.sln
  modules/evaluation-server/src/Api/Middlewares/StreamingMiddleware.cs
  modules/evaluation-server/src/Api/ServicesRegister.cs
  modules/evaluation-server/src/Domain/Domain.csproj
  modules/evaluation-server/src/Domain/WebSockets/Connection.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionHandler.Log.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionHandler.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionManager.Log.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionManager.cs
  modules/evaluation-server/src/Domain/WebSockets/Message.cs
  modules/evaluation-server/src/Domain/WebSockets/MessageFragment.cs
  modules/evaluation-server/src/Domain/WebSockets/MessageProcessor.cs
  modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ConnectionTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/EchoTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ProcessMessageTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/StreamingTestApp.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ValidationTests.cs
  modules/evaluation-server/tests/Application.UnitTests/Application.UnitTests.csproj
  modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionManagerTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/ConnectionTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/MessageFragmentTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/WebSockets/RequestHandlerTests.cs
  modules/evaluation-server/tests/TestBase/InMemoryFakeLogger.cs
  modules/evaluation-server/tests/TestBase/TestBase.csproj
Labels: Evaluation Server

#26 🐛 fix error when docker build evaluation server
  modules/evaluation-server/EvaluationServer.sln
  modules/evaluation-server/depoly/Dockerfile
  modules/evaluation-server/src/Domain/Utils/ExtensionMethods/DataTimeExtensions.cs
  modules/evaluation-server/src/Domain/WebSockets/RequestHandler.cs
  modules/evaluation-server/tests/Application.IntegrationTests/TestApp.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ConnectionTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/EchoTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/ProcessMessageTests.cs
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/StreamingTestApp.cs
  modules/evaluation-server/tests/Domain.UnitTests/Utils/DateTimeExtensionTests.cs
Labels: bug, Evaluation Server

#27 ✨ Api health checks
  modules/back-end/README.md
  modules/back-end/deploy/Dockerfile
  modules/back-end/src/Api/Controllers/WeatherForecastController.cs
  modules/back-end/src/Api/Program.cs
  modules/back-end/src/Api/Properties/launchSettings.json
  modules/back-end/src/Api/WeatherForecast.cs
  modules/back-end/tests/Application.IntegrationTests/SmokeTests.cs
Labels: API

#36 ✨ Login By Password Api
  modules/back-end/.gitignore
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Api/Controllers/ApiControllerBase.cs
  modules/back-end/src/Api/Controllers/ApiResponse.cs
  modules/back-end/src/Api/Controllers/BasicController.cs
  modules/back-end/src/Api/Controllers/ConfigSwaggerOptions.cs
  modules/back-end/src/Api/Controllers/IdentityController.cs
  modules/back-end/src/Api/Middlewares/ApiExceptionMiddlewareExtension.cs
  modules/back-end/src/Api/Program.cs
  modules/back-end/src/Api/Properties/launchSettings.json
  modules/back-end/src/Api/Usings.cs
  modules/back-end/src/Api/appsettings.json
  modules/back-end/src/Application/Application.csproj
  modules/back-end/src/Application/Bases/Behaviours/ValidationBehaviour.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/ConfigureServices.cs
  modules/back-end/src/Application/Identity/LoginByPassword.cs
  modules/back-end/src/Application/Identity/LoginResult.cs
  modules/back-end/src/Application/Identity/LoginToken.cs
  modules/back-end/src/Application/Services/IIdentityService.cs
  modules/back-end/src/Application/Usings.cs
  modules/back-end/src/Domain/Identity/IdentityOptions.cs
  modules/back-end/src/Domain/Identity/User.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Identity/IUserStore.cs
  modules/back-end/src/Infrastructure/Identity/IdentityService.cs
  modules/back-end/src/Infrastructure/Identity/MongoDbUserStore.cs
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/src/Infrastructure/MongoDb/MongoDbClient.cs
  modules/back-end/src/Infrastructure/MongoDb/MongoDbOptions.cs
  modules/back-end/src/Infrastructure/MongoDb/seed.script
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityApp.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Initialization.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.ApiVersioning.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.HandleException.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/IdentityControllerTests.LoginByPassword_RequestValidation.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/IdentityControllerTests.LoginByPassword_Success.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Stubs/InMemoryUserStore.cs
  modules/back-end/tests/Application.IntegrationTests/Stubs/TestPasswordHasher.cs
  modules/back-end/tests/Application.IntegrationTests/TestApp.cs
  modules/back-end/tests/Application.IntegrationTests/Usings.cs
  modules/back-end/tests/Application.UnitTests/Identity/IdentityServiceTests.cs
  modules/back-end/tests/Application.UnitTests/Usings.cs
  modules/back-end/tests/TestBase/TestBase.csproj
  modules/back-end/tests/TestBase/TestLogger.cs
Labels: API

#47 ✨ feat(ui/docker-compose): added ui to docker compose
  docker-compose-dev.yml
Labels: UI

#50 ✨ Api add cors support
  modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Api/appsettings.json
Labels: API

#51 ✨ Api Authentication & Authorization
  modules/back-end/src/Api/Controllers/ApiControllerBase.cs
  modules/back-end/src/Api/Controllers/BasicController.cs
  modules/back-end/src/Api/Setup/ApiAuthorizationResultHandler.cs
  modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Api/appsettings.json
  modules/back-end/src/Application/ConfigureServices.cs
  modules/back-end/src/Application/Services/IIdentityService.cs
  modules/back-end/src/Application/Users/CurrentUser.cs
  modules/back-end/src/Application/Users/ICurrentUser.cs
  modules/back-end/src/Domain/Identity/JwtOptions.cs
  modules/back-end/src/Domain/Users/User.cs
  modules/back-end/src/Domain/Users/UserClaims.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Identity/IdentityService.cs
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/src/Infrastructure/MongoDb/MongoDbClient.cs
  modules/back-end/src/Infrastructure/Users/IUserStore.cs
  modules/back-end/src/Infrastructure/Users/MongoDbUserStore.cs
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityApp.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Initialization.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.ApiVersioning.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.Authorized.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.HandleException.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.NeedAuthentication.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Stubs/InMemoryUserStore.cs
  modules/back-end/tests/Application.IntegrationTests/Stubs/TestPasswordHasher.cs
  modules/back-end/tests/Application.IntegrationTests/TestApp.cs
  modules/back-end/tests/Application.UnitTests/Identity/IdentityServiceTests.cs
Labels: API

#54 🐛 Fix (UI): fixed pagination button position
  modules/front-end/src/styles.less
Labels: UI

#55 ✨ feat(ui/font): use different font for en and zh locales
  modules/front-end/angular.json
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.less
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.less
  modules/front-end/src/app/features/safe/iam/groups/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/iam/policies/details/permission/permission.component.less
  modules/front-end/src/app/features/safe/iam/policies/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/iam/team/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.less
  modules/front-end/src/styles-common.less
  modules/front-end/src/styles-zh.less
  modules/front-end/src/styles.less
Labels: UI
