Repository featbit/featbit, pull requests merged in 2022-11, with the labels that each got.

#91 🧹 Refactor metric page
  modules/back-end/src/Application/ExperimentMetrics/ExperimentMetricFilter.cs
  modules/back-end/src/Infrastructure/ExperimentMetrics/ExperimentMetricService.cs
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/core/services/experiment.service.ts
  modules/front-end/src/app/core/services/metric.service.ts
  modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.html
  modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.ts
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.ts
  modules/front-end/src/app/features/safe/experiments/types.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/experimentations.ts
Labels: UI, API

#94 🐛 fix(ui/experimentation): fixed experimentation wrongly loaded into experimentation tab of a feature flag bug
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
Labels: UI

#92 📖 🏗 🔧Enable access of interactive demo hosted in remote server
  docker-compose-dev.yml
  modules/front-end/Dockerfile
  modules/front-end/src/app/core/components/guide/guide.component.html
  modules/front-end/src/app/core/components/guide/guide.component.ts
  modules/front-end/src/environments/environment.prod.ts
  modules/front-end/src/environments/environment.ts
Labels: documentation, demo

#95 ✨ feat(ui): Before removing a variation from a feature flag, verify if it is used by an experiment baseline
  modules/back-end/src/Api/Controllers/ExperimentController.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Bases/Models/PagedRequest.cs
  modules/back-end/src/Application/FeatureFlags/GetFeatureFlagVariationExptReferences.cs
  modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
  modules/front-end/src/app/core/components/find-rule/targeted-user-table/targeted-user-table.component.ts
  modules/front-end/src/app/core/services/experiment.service.ts
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.html
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.less
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
Labels: UI, API

#93 ✨ get end-user's flags & segments
  modules/back-end/src/Api/Controllers/EndUserController.cs
  modules/back-end/src/Application/EndUsers/EndUserFlagVm.cs
  modules/back-end/src/Application/EndUsers/EndUserSegmentVm.cs
  modules/back-end/src/Application/EndUsers/GetEndUserFlags.cs
  modules/back-end/src/Application/EndUsers/GetEndUserSegments.cs
  modules/back-end/src/Application/Services/IEvaluator.cs
  modules/back-end/src/Domain/EndUsers/EndUser.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
  modules/back-end/src/Domain/FeatureFlags/RolloutVariation.cs
  modules/back-end/src/Domain/FeatureFlags/UserVariation.cs
  modules/back-end/src/Domain/Segments/Segment.cs
  modules/back-end/src/Domain/Targeting/Condition.cs
  modules/back-end/src/Domain/Targeting/Operator.cs
  modules/back-end/src/Domain/Targeting/OperatorTypes.cs
  modules/back-end/src/Domain/Targeting/SplittingAlgorithm.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Targeting/Evaluator.cs
  modules/front-end/src/app/core/components/props-drawer/props-drawer.component.ts
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.html
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.spec.ts
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.ts
  modules/front-end/src/app/core/services/env-user.service.ts
  modules/front-end/src/app/features/safe/end-users/index/index.component.html
  modules/front-end/src/app/features/safe/end-users/types/user-segments-flags.ts
Labels: UI, API

#109 🐛Fix(api): fixed bug that user name not displayed on team and policy detail page's team tab
  modules/back-end/src/Application/Groups/GroupMemberVm.cs
  modules/back-end/src/Application/Policies/PolicyMember.cs
  modules/back-end/src/Infrastructure/Groups/GroupService.cs
  modules/back-end/src/Infrastructure/Policies/PolicyService.cs
Labels: API

#110 ✨ Feat(ui): user smooth curve for charts
  modules/front-end/src/app/core/components/g2-chart/g2-line-chart/g2-line-chart.component.ts
  modules/front-end/src/app/core/components/g2-chart/g2-line-chart/g2-line-chart.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/reporting/reporting.component.ts
Labels: question

#114 ✨ reset user password
  modules/back-end/src/Api/Controllers/IdentityController.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Identity/ResetPassword.cs
  modules/back-end/src/Application/Identity/ResetPasswordResult.cs
  modules/front-end/package-lock.json
  modules/front-end/src/app/core/services/identity.service.ts
  modules/front-end/src/app/core/services/user.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.less
  modules/front-end/src/app/features/safe/organizations/organizations.module.ts
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.html
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.less
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
  modules/front-end/src/app/features/safe/organizations/types/profiles.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: UI, API

#116 ✨ Feat(ui): added docker compose file for prod
  .github/workflows/publish-docker-images.yml
  docker-compose-dev.yml
  docker-compose.yml
  modules/front-end/Dockerfile
  modules/front-end/package.json
  modules/front-end/src/assets/env.js
  modules/front-end/src/assets/env.template.js
  modules/front-end/src/environments/environment.prod.ts
  modules/front-end/src/environments/environment.ts
  modules/front-end/src/index.html
Labels: UI

#117 Updated Readme
  README.md
  why_featbit.md
Labels: documentation

#118 📖 Updated Docs/readme
  README.md
  what_is_featbit.md
Labels: documentation

#119 📖Updated Docs/readme
  README.md
Labels: documentation

#123 📖 Update README.md
  README.md
Labels: documentation

#127 🐛 Implement delete member api
  modules/back-end/src/Api/Controllers/MemberController.cs
  modules/back-end/src/Application/Members/DeleteMember.cs
  modules/back-end/src/Application/Services/IMemberService.cs
  modules/back-end/src/Infrastructure/Members/MemberService.cs
Labels: API
