Repository featbit/featbit, pull requests merged in 2022-12, with the labels that each got.

#130 ✨ feat(ui): rename feature flag reporting tab to insights
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Application/FeatureFlags/GetInsights.cs
  modules/back-end/src/Application/FeatureFlags/InsightsVm.cs
  modules/back-end/src/Application/Services/IOlapService.cs
  modules/back-end/src/Domain/FeatureFlags/InsightsParam.cs
  modules/back-end/src/Infrastructure/Experiments/OlapService.cs
  modules/front-end/src/app/core/services/env-user.service.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/details-routing.module.ts
  modules/front-end/src/app/features/safe/feature-flags/details/details.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/details.module.ts
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/insights/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#132 📖 docs: add design contribution guidelines
  DESIGN.md
  README.md
Labels: documentation, design

#134 📖 Added design folder and readme
  .design/README.md
Labels: documentation, design

#135 📖 removed design.md
  DESIGN.md
Labels: documentation, design

#136 📖 Update Docs/readme
  README.md
Labels: documentation

#133 ✨ ui/ux improvements for Sprint 3
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.less
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.less
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.module.ts
  modules/front-end/src/app/features/safe/feature-flags/types/details.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.ts
  modules/front-end/src/app/features/safe/iam/groups/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/iam/groups/index/index.component.html
  modules/front-end/src/app/features/safe/iam/policies/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/iam/policies/index/index.component.html
  modules/front-end/src/app/features/safe/iam/team/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/iam/team/index/index.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.less
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/segments/index/index.component.html
  modules/front-end/src/app/shared/utils/index.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/variables.less
Labels: UI

#145 🐛 close experiment drawer when user clicks mask
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: API

#147 📖 Docs/readme
  README.md
Labels: documentation

#148 📖 Update README.md
  README.md
Labels: documentation

#149 📖 Update README.md
  README.md
Labels: documentation

#172 🐛 cannot save flag change
  modules/front-end/src/app/shared/utils/diff/feature-flag.differ.ts
Labels: bug

#174 🏗 always use latest image
  docker-compose-dev.yml
  docker-compose.yml
Labels: enhancement

#161 ✨ add more feature flag audit logs
  modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
  modules/back-end/src/Application/FeatureFlags/ToggleFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
  modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
Labels: UI, API

#180 🐛 keep built-in policy's id consistent
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  modules/back-end/src/Domain/Policies/BuiltInPolicy.cs
Labels: bug

#181 feat(ui): extract audit log list to a component
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.html
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.less
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/features/safe/audit-logs/index/index.component.html
  modules/front-end/src/app/features/safe/audit-logs/index/index.component.less
  modules/front-end/src/app/features/safe/audit-logs/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/details.module.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#182 ✨ audit logs for segment
  modules/back-end/src/Application/Segments/ArchiveSegment.cs
  modules/back-end/src/Application/Segments/CreateSegment.cs
  modules/back-end/src/Application/Segments/UpdateSegment.cs
  modules/back-end/src/Domain/AuditLogs/AuditLog.cs
  modules/back-end/src/Domain/AuditLogs/AuditLogRefTypes.cs
  modules/back-end/src/Domain/AuditLogs/Keywords.cs
  modules/back-end/src/Domain/Segments/Segment.cs
  modules/front-end/src/app/core/components/audit-log/audit-log.component.html
  modules/front-end/src/app/core/components/audit-log/audit-log.component.less
  modules/front-end/src/app/core/components/audit-log/audit-log.component.ts
  modules/front-end/src/app/core/components/audit-log/types.ts
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.html
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.ts
  modules/front-end/src/app/core/components/change-list/change-list.component.html
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/change-review/change-review.component.less
  modules/front-end/src/app/core/components/change-review/change-review.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/diff-factory.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/segments/details/audit-logs/audit-logs.component.html
  modules/front-end/src/app/features/safe/segments/details/audit-logs/audit-logs.component.less
  modules/front-end/src/app/features/safe/segments/details/audit-logs/audit-logs.component.ts
  modules/front-end/src/app/features/safe/segments/details/details-routing.module.ts
  modules/front-end/src/app/features/safe/segments/details/details.component.html
  modules/front-end/src/app/features/safe/segments/details/details.module.ts
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.less
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/segments/types/segments-index.ts
  modules/front-end/src/app/shared/diff/feature-flag.differ.ts
  modules/front-end/src/app/shared/diff/index.ts
  modules/front-end/src/app/shared/diff/segment.differ.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, API

#183 🐛 fix(ui): fixed bug that segment setting page and targeting page not sync
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.less
  modules/front-end/src/app/core/services/message-queue.service.ts
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
Labels: UI
