Repository featbit/featbit, pull requests merged in 2023-01, with the labels that each got.

#185 feat: segment enhancement
  modules/back-end/src/Api/Controllers/SegmentController.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Segments/DeleteSegment.cs
  modules/back-end/src/Application/Segments/RestoreSegment.cs
  modules/back-end/src/Application/Segments/SegmentFilter.cs
  modules/back-end/src/Application/Services/ISegmentService.cs
  modules/back-end/src/Domain/AuditLogs/AuditLog.cs
  modules/back-end/src/Domain/Segments/Segment.cs
  modules/back-end/src/Infrastructure/Segments/SegmentService.cs
  modules/front-end/src/app/core/services/segment.service.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/segments/index/index.component.html
  modules/front-end/src/app/features/safe/segments/index/index.component.ts
  modules/front-end/src/app/features/safe/segments/index/index.module.ts
  modules/front-end/src/app/features/safe/segments/types/segments-index.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, API

#187 ✨ feat: add ff list page filter params to query string
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/switch-index.ts
  modules/front-end/src/app/shared/utils/index.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#189 🐛 fix: fixed the scroll bar not displaying bug on feature flag history tab
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#191 fix: put the feature flag history tab loader at the center of the page
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/audit-logs/audit-logs.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#190 ✨ feat: added breadcrumb
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/bread-crumb.service.ts
  modules/front-end/src/app/features/safe/end-users/index/index.component.html
  modules/front-end/src/app/features/safe/end-users/index/index.component.ts
  modules/front-end/src/app/features/safe/experiments/experiments-routing.module.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index-routing.module.ts
  modules/front-end/src/app/features/safe/iam/groups/details/details-routing.module.ts
  modules/front-end/src/app/features/safe/iam/groups/details/team/team.component.ts
  modules/front-end/src/app/features/safe/iam/iam-routing.module.ts
  modules/front-end/src/app/features/safe/iam/policies/details/details-routing.module.ts
  modules/front-end/src/app/features/safe/iam/policies/details/team/team.component.ts
  modules/front-end/src/app/features/safe/iam/team/details/details-routing.module.ts
  modules/front-end/src/app/features/safe/iam/team/index/index.component.ts
  modules/front-end/src/app/features/safe/organizations/organizations-routing.module.ts
  modules/front-end/src/app/features/safe/safe-routing.module.ts
  modules/front-end/src/app/features/safe/safe.component.ts
  modules/front-end/src/app/features/safe/segments/details/details-routing.module.ts
  modules/front-end/src/app/features/safe/segments/index/index-routing.module.ts
  modules/front-end/src/app/features/safe/segments/segments-routing.module.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#192 🖍 remove redundant padding style for main content area
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.html
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.less
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.ts
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/features/safe/audit-logs/index/index.component.html
  modules/front-end/src/app/features/safe/data-sync/data-sync.component.html
  modules/front-end/src/app/features/safe/data-sync/data-sync.component.less
  modules/front-end/src/app/features/safe/end-users/details/details.component.html
  modules/front-end/src/app/features/safe/end-users/details/details.component.less
  modules/front-end/src/app/features/safe/end-users/index/index.component.less
  modules/front-end/src/app/features/safe/experiments/experiments.component.html
  modules/front-end/src/app/features/safe/experiments/experiments.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/details.component.less
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.less
  modules/front-end/src/app/features/safe/iam/groups/details/details.component.less
  modules/front-end/src/app/features/safe/iam/iam.component.less
  modules/front-end/src/app/features/safe/iam/policies/details/details.component.less
  modules/front-end/src/app/features/safe/iam/team/details/details.component.less
  modules/front-end/src/app/features/safe/organizations/organizations.component.html
  modules/front-end/src/app/features/safe/organizations/organizations.component.less
  modules/front-end/src/app/features/safe/safe.component.less
  modules/front-end/src/app/features/safe/segments/details/details.component.less
  modules/front-end/src/app/features/safe/segments/index/index.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#193 ✨ feat: support multiple secrets
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  modules/back-end/src/Api/Controllers/EnvironmentSecretController.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Environments/AddSecret.cs
  modules/back-end/src/Application/Environments/DeleteSecret.cs
  modules/back-end/src/Application/Environments/UpdateSecret.cs
  modules/back-end/src/Domain/Environments/Environment.cs
  modules/back-end/src/Domain/Environments/Secret.cs
  modules/back-end/src/Domain/Environments/SecretTypes.cs
  modules/front-end/angular.json
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.html
  modules/front-end/src/app/core/services/env-secret.service.ts
  modules/front-end/src/app/core/services/env.service.ts
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/core/translations/iam-action.translation.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/types.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.less
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/app/shared/permissions.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: UI, API

#194 🧹 add feature flag key validation for api
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
Labels: API

#202 🧹removed translation pipe for resource type and actions
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
  modules/front-end/src/app/core/pipes/translation.pipe.ts
  modules/front-end/src/app/core/translations/iam-action.translation.ts
  modules/front-end/src/app/core/translations/resource-type.translation.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/actions-selector/actions-selector.component.html
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.html
  modules/front-end/src/app/features/safe/iam/components/policy-editor/types.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.html
  modules/front-end/src/app/shared/permissions.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement

#203 🐛 force to logout after reinitialized mongodb data
  modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
  modules/front-end/src/app/core/services/identity.service.ts
Labels: UI

#205 🗑️ removed view matched users button on rule definition for feature flag and segment
  modules/front-end/src/app/core/components/find-rule/find-rule.component.html
  modules/front-end/src/app/core/components/find-rule/find-rule.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#208 🐛 fixed audit log displaying bug
  modules/front-end/src/app/core/components/audit-log/audit-log.component.ts
  modules/front-end/src/app/core/components/change-list/change-list.component.html
  modules/front-end/src/app/core/components/change-list/change-list.component.less
  modules/front-end/src/app/core/components/change-list/change-list.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#209 🐛 fixed cannot recreate experiment bug
  modules/back-end/src/Application/Experiments/CreateExperiment.cs
Labels: API

#216 📖 Readme, corrected twitter badge's URL
  README.md
Labels: bug, documentation

#213 ✨ feat: encode splitting key with utf8
  modules/back-end/src/Domain/Targeting/SplittingAlgorithm.cs
  modules/back-end/tests/Domain.UnitTests/Targeting/SplittingAlgorithmTests.cs
  modules/evaluation-server/src/Domain/Core/SplittingAlgorithm.cs
  modules/evaluation-server/tests/Domain.UnitTests/Core/SplittingAlgorithmTest.cs
Labels: enhancement

#215 ✨ feat: rollout with custom key
  modules/back-end/src/Domain/FeatureFlags/Fallthrough.cs
  modules/back-end/src/Domain/FeatureFlags/RolloutVariation.cs
  modules/back-end/src/Domain/Targeting/DispatchAlgorithm.cs
  modules/back-end/src/Domain/Targeting/TargetRule.cs
  modules/back-end/src/Infrastructure/Targeting/Evaluator.cs
  modules/back-end/tests/Domain.UnitTests/Targeting/DispatchAlgorithmTests.cs
  modules/evaluation-server/src/Domain/Core/DispatchAlgorithm.cs
  modules/evaluation-server/src/Domain/Core/UserVariation.cs
  modules/evaluation-server/src/Domain/EndUsers/EndUser.cs
  modules/evaluation-server/src/Domain/EndUsers/EndUserConsts.cs
  modules/evaluation-server/src/Infrastructure/Services/EvaluationService.cs
  modules/evaluation-server/tests/Domain.UnitTests/Core/DispatchAlgorithmTest.cs
  modules/front-end/package.json
  modules/front-end/src/app/core/components/change-list/change-list.component.html
  modules/front-end/src/app/core/components/change-list/change-list.component.less
  modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.html
  modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.less
  modules/front-end/src/app/core/components/find-rule/find-rule.component.html
  modules/front-end/src/app/core/components/find-rule/find-rule.component.ts
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.html
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.less
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/details.ts
  modules/front-end/src/app/features/safe/segments/index/index.component.less
  modules/front-end/src/app/shared/diff/feature-flag.differ.ts
  modules/front-end/src/app/shared/diff/index.ts
  modules/front-end/src/app/shared/diff/types.ts
  modules/front-end/src/app/shared/rules.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, API, Evaluation Server

#218 🐛 fix: removed extra space before key in user property preset value editing modal
  modules/front-end/src/app/core/components/props-drawer/props-drawer.component.html
Labels: UI

#220 📖 doc: README.md typo fix
  README.md
Labels: documentation

#212 📖 doc: guide for setting up development environment
  CONTRIBUTING.md
  Development.md
  modules/front-end/README.md
Labels: documentation

#223 📖 doc: how to contribute
  CONTRIBUTING.md
Labels: documentation
