Repository featbit/featbit, pull requests merged in 2023-07, with the labels that each got.

#427 🐛 fix: the get started page could not create new feature flag
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.ts
  modules/front-end/src/app/features/safe/get-started/steps/steps.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug

#426 ✨ feat: display variation names instead of valuess in insights page end user table
  modules/back-end/src/Application/EndUsers/GetFeatureFlagEndUserList.cs
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#429 🧹 refactor: upgrade to angular 16
  modules/front-end/package-lock.json
  modules/front-end/package.json
  modules/front-end/tsconfig.json
Labels: ui

#430 🐛 fix: type mismatch in instantiating feature flag filter from query string
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug

#434 🖍 fix: truncate long variation value with ellipsis
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#435 🖍 refactor: update featbit logo
  modules/front-end/src/app/core/components/menu/menu.component.html
  modules/front-end/src/app/features/login/login.component.html
  modules/front-end/src/assets/logo/featbit-logo-text.svg
  modules/front-end/src/assets/logo/logo.svg
  modules/front-end/src/assets/logo/logo_black_transparant.png
  modules/front-end/src/assets/logo/logo_black_transparent.svg
  modules/front-end/src/assets/logo/logo_title_black.svg
  modules/front-end/src/assets/logo/logo_white_colorful.png
  modules/front-end/src/assets/logo/logo_white_shadow_transparant.png
  modules/front-end/src/assets/logo/logo_white_transparant.png
  modules/front-end/src/assets/logo/logo_with_fulltext.png
  modules/front-end/src/assets/logo/logo_with_title.png
  modules/front-end/src/index.html
Labels: ui

#436 ✨ UI feat: add icon on header that redirect on the docs
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, points:4

#439 🐛 fix: current project & env name not updated
  modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#442 🖍 style: make logo smaller
  modules/front-end/src/app/core/components/menu/menu.component.less
  modules/front-end/src/app/features/login/login.component.less
Labels: ui

#441 🧹 refactor: replace class-based resolvers with functional resolvers
  modules/front-end/src/app/app-routing.module.ts
  modules/front-end/src/app/app.module.ts
  modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
  modules/front-end/src/app/core/services/identity.service.ts
  modules/front-end/src/app/features/safe/end-users/details/details.resolver.ts
  modules/front-end/src/app/features/safe/onboarding/onboarding.component.ts
  modules/front-end/src/app/features/safe/safe.component.ts
Labels: ui

#444 ✨ feat: made UI to return 444 when seeing malicious scan requests
  modules/front-end/nginx.conf
Labels: ui

#447 ✨ feat: integrate serilog for evaluation server
  modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Api/Program.cs
  modules/evaluation-server/src/Api/Setup/HostBuilder.cs
  modules/evaluation-server/src/Api/Setup/MiddlewaresRegister.cs
  modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
Labels: enhancement

#448 🐛Fixed user cannot switch to environment even has the access env permission bug
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#449 🔥 hotfix: ui cannot start in azure app service
  modules/front-end/nginx.conf
Labels: bug

#450 🐛fix: check if user has the access permission to the env
  modules/front-end/src/app/app-routing.module.ts
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#443 🧹 refactor: code clean for front end project
  modules/front-end/src/app/app-routing.module.ts
  modules/front-end/src/app/app.module.ts
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/target-user/target-user.component.ts
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/app/core/guards/login.guard.ts
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/app/features/login/login.component.ts
  modules/front-end/src/app/features/safe/end-users/index/index.component.ts
  modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.ts
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.ts
  modules/front-end/src/app/features/safe/experiments/types.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/onboarding/complete/complete.component.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#451 🧹 tech-debt: replace class based CanActivate by function
  modules/front-end/src/app/app-routing.module.ts
  modules/front-end/src/app/core/guards/accessTokens.guard.ts
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/app/core/guards/iam.guard.ts
  modules/front-end/src/app/core/guards/relayProxies.guard.ts
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/features/safe/integrations/integrations-routing.module.ts
  modules/front-end/src/app/features/safe/safe-routing.module.ts
Labels: ui

#432 🐛 fix: organization name doesn't update after another user update it …
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, points:8

#453 🐛 fix: organizations are not loaded after user refresh the page
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/app/core/services/identity.service.ts
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#452 🧹 refactor: change the way we control project and env permissions
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
  kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.ts
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, breaking-change

#455 🔥 fix: user cannot complete onboarding
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.html
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.less
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#456 ✨ feat: check if key has been used
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Environments/CreateEnvironment.cs
  modules/back-end/src/Application/Environments/IsKeyUsed.cs
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/IsFeatureFlagKeyUsed.cs
  modules/back-end/src/Application/Organizations/Onboarding.cs
  modules/back-end/src/Application/Projects/CreateProject.cs
  modules/back-end/src/Application/Projects/IsKeyUsed.cs
  modules/back-end/src/Application/Services/IEnvironmentService.cs
  modules/back-end/src/Application/Services/IFeatureFlagService.cs
  modules/back-end/src/Application/Services/IProjectService.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
  modules/back-end/src/Infrastructure/Environments/EnvironmentService.cs
  modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs
  modules/back-end/src/Infrastructure/Projects/ProjectService.cs
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/app/core/interceptors/request-response.interceptor.ts
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/features/safe/onboarding/onboarding.component.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement

#457 🏗 infra: setting up reverse proxy for API and evaluation server
  modules/front-end/nginx.conf
  modules/front-end/src/environments/environment.prod.ts
  modules/front-end/src/environments/environment.ts
Labels: enhancement, ui

#458 ✨ feat: sync to all agent
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.html
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.ts
  modules/front-end/src/environments/environment.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#459 🏗 infra: add nginx gateway
  modules/front-end/nginx-gateway.conf
  modules/front-end/nginx.conf
Labels: enhancement, ui

#462 🏗 infra: nginx cache control and gzip
  modules/front-end/nginx.conf
Labels: enhancement, ui

#461 🐛 fix: Chinese translation typo
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#463 🏗 infra: UI log 404 instead of error when non-existing image, css and js files are requested
  modules/front-end/nginx.conf
Labels: ui

#464 🧹 enhancement: improve loading time & nginx 404
  modules/front-end/nginx.conf
  modules/front-end/src/app/app-routing.module.ts
Labels: enhancement, ui

#465 🏗 infra: improve nginx settings
  modules/front-end/nginx.conf
Labels: ui
