Repository featbit/featbit, pull requests merged in 2023-10, with the labels that each got.

#503 🧹 refactor: change the way we configure kafka consumer and producer
  docker-compose-pro.yml
  docker/composes/README.md
  modules/back-end/README.md
  modules/back-end/src/Api/appsettings.Development.json
  modules/back-end/src/Api/appsettings.json
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageProducer.cs
  modules/back-end/tests/Application.IntegrationTests/Configuration/KafkaConfigTests.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/KafkaConfigTests.DefaultProducerConsumerConfig.verified.txt
  modules/data-analytics/Dockerfile
  modules/evaluation-server/README.md
  modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
  modules/evaluation-server/src/Api/appsettings.Development.json
  modules/evaluation-server/src/Api/appsettings.json
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageProducer.cs
Labels: breaking-change, infrastructure

#502 ✨ feat: license check
  modules/back-end/src/Api/Authorization/LicenseRequirement.cs
  modules/back-end/src/Api/Authorization/LicenseRequirementHandler.cs
  modules/back-end/src/Api/Controllers/BasicController.cs
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Api/Controllers/OrganizationController.cs
  modules/back-end/src/Api/Controllers/SsoController.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Api/appsettings.Development.json
  modules/back-end/src/Api/appsettings.json
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Caches/ICacheService.cs
  modules/back-end/src/Application/FeatureFlags/UpdateTargeting.cs
  modules/back-end/src/Application/Organizations/Onboarding.cs
  modules/back-end/src/Application/Organizations/OrganizationVm.cs
  modules/back-end/src/Application/Organizations/UpdateOrganizationLicense.cs
  modules/back-end/src/Application/Organizations/UpdateOrganizationName.cs
  modules/back-end/src/Application/Services/ILicenseService.cs
  modules/back-end/src/Domain/FlagSchedules/FlagSchedule.cs
  modules/back-end/src/Domain/Organizations/License.cs
  modules/back-end/src/Domain/Organizations/LicenseFeatures.cs
  modules/back-end/src/Domain/Organizations/LicenseVerifier.cs
  modules/back-end/src/Domain/Organizations/Organization.cs
  modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleWorker.cs
  modules/back-end/src/Infrastructure/License/LicenseService.cs
  modules/back-end/src/Infrastructure/Redis/RedisCacheService.cs
  modules/back-end/src/Infrastructure/Redis/RedisKeys.cs
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.NeedLicense.verified.txt
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/change-review/change-review.component.ts
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/license/license.component.html
  modules/front-end/src/app/core/components/license/license.component.less
  modules/front-end/src/app/core/components/license/license.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/features/login/do-login/do-login.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.html
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.less
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/app/shared/utils/index.ts
  modules/front-end/src/assets/icons/icon-id.svg
  modules/front-end/src/assets/icons/icon-license.svg
  modules/front-end/src/environments/environment.prod.ts
  modules/front-end/src/environments/environment.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: from-discussion

#504 ✨ feat: forbid sso users to reset password
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
  kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
  modules/back-end/src/Api/Controllers/SsoController.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/Identity/ResetPassword.cs
  modules/back-end/src/Application/Organizations/AddUser.cs
  modules/back-end/src/Application/Services/IIdentityService.cs
  modules/back-end/src/Application/Users/Profile.cs
  modules/back-end/src/Domain/Users/User.cs
  modules/back-end/src/Domain/Users/UserOrigin.cs
  modules/back-end/src/Infrastructure/Identity/IdentityService.cs
  modules/back-end/src/Infrastructure/MongoDb/ClassMaps.cs
  modules/back-end/src/Infrastructure/MongoDb/seed-for-dev.js
  modules/back-end/tests/Application.IntegrationTests/Snapshots/UserControllerTests.GetUserProfile.verified.txt
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.html
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
  modules/front-end/src/app/features/safe/organizations/types/profiles.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/app/shared/utils/index.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, api

#505 🧹 refactor: move feedback from navigation bar to left sidebar
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/menu/menu.component.html
  modules/front-end/src/app/core/components/menu/menu.component.ts
  modules/front-end/src/assets/icons/icon-medal.svg
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#500 🧹 refactor: enhance clickhouse cluster support
  docker/composes/docker-compose-pro-kafka-3-brokers-clickhouse-3-shards.yml
  infra/clickhouse/shards/clickhouse-blue-1/docker_related_config.xml
  infra/clickhouse/shards/clickhouse-blue-1/enable_keeper.xml
  infra/clickhouse/shards/clickhouse-blue-1/macros.xml
  infra/clickhouse/shards/clickhouse-blue-1/remote_servers.xml
  infra/clickhouse/shards/clickhouse-blue-1/use_keeper.xml
  infra/clickhouse/shards/clickhouse-blue-2/docker_related_config.xml
  infra/clickhouse/shards/clickhouse-blue-2/enable_keeper.xml
  infra/clickhouse/shards/clickhouse-blue-2/macros.xml
  infra/clickhouse/shards/clickhouse-blue-2/remote_servers.xml
  infra/clickhouse/shards/clickhouse-blue-2/use_keeper.xml
  infra/clickhouse/shards/clickhouse-green-1/docker_related_config.xml
  infra/clickhouse/shards/clickhouse-green-1/enable_keeper.xml
  infra/clickhouse/shards/clickhouse-green-1/macros.xml
  infra/clickhouse/shards/clickhouse-green-1/remote_servers.xml
  infra/clickhouse/shards/clickhouse-green-1/use_keeper.xml
  infra/clickhouse/shards/clickhouse-green-2/docker_related_config.xml
  infra/clickhouse/shards/clickhouse-green-2/macros.xml
  infra/clickhouse/shards/clickhouse-green-2/remote_servers.xml
  infra/clickhouse/shards/clickhouse-green-2/use_keeper.xml
  infra/clickhouse/shards/clickhouse-orange-1/docker_related_config.xml
  infra/clickhouse/shards/clickhouse-orange-1/macros.xml
  infra/clickhouse/shards/clickhouse-orange-1/remote_servers.xml
  infra/clickhouse/shards/clickhouse-orange-1/use_keeper.xml
  infra/clickhouse/shards/clickhouse-orange-2/docker_related_config.xml
  infra/clickhouse/shards/clickhouse-orange-2/macros.xml
  infra/clickhouse/shards/clickhouse-orange-2/remote_servers.xml
  infra/clickhouse/shards/clickhouse-orange-2/use_keeper.xml
  infra/kafka/config.properties
  modules/data-analytics/Dockerfile
  modules/data-analytics/app/clickhouse/client.py
  modules/data-analytics/app/clickhouse/commands/migrate.py
  modules/data-analytics/app/setting.py
  modules/data-analytics/docker-entrypoint.sh
  modules/data-analytics/requirements.txt
Labels: enhancement

#507 🖍 style: use the same icon for enterprise and non enterprise org
  modules/front-end/src/app/core/components/header/header.component.html
Labels: bug, ui

#511 🧹 refactor: change feature flag trigger method from put to post
  modules/back-end/src/Api/Controllers/TriggerController.cs
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
Labels: api, breaking-change

#508 ✨ feat: disable organization creation
  modules/back-end/src/Api/Controllers/OrganizationController.cs
  modules/back-end/src/Domain/Organizations/LicenseFeatures.cs
  modules/front-end/src/app/core/components/license/license.component.html
  modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.ts
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.html
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.less
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, api

#512 🧹 refactor: connect sdk instruction typo
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
Labels: bug

#516 ✨ feat: fallback to mongodb when redis is unavailable
  modules/evaluation-server/src/Api/Properties/launchSettings.json
  modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
  modules/evaluation-server/src/Api/appsettings.Development.json
  modules/evaluation-server/src/Api/appsettings.json
  modules/evaluation-server/src/Domain/Shared/IStore.cs
  modules/evaluation-server/src/Infrastructure/Fakes/FakeStore.cs
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/src/Infrastructure/MongoDb/BsonDocumentExtensions.cs
  modules/evaluation-server/src/Infrastructure/MongoDb/IMongoDbClient.cs
  modules/evaluation-server/src/Infrastructure/MongoDb/MongoDbClient.cs
  modules/evaluation-server/src/Infrastructure/MongoDb/MongoDbOptions.cs
  modules/evaluation-server/src/Infrastructure/Redis/IRedisClient.cs
  modules/evaluation-server/src/Infrastructure/Redis/RedisClient.cs
  modules/evaluation-server/src/Infrastructure/Redis/RedisMessageConsumer.cs
  modules/evaluation-server/src/Infrastructure/Redis/RedisMessageProducer.cs
  modules/evaluation-server/src/Infrastructure/Store/HybridStore.cs
  modules/evaluation-server/src/Infrastructure/Store/MongoDbStore.cs
  modules/evaluation-server/src/Infrastructure/Store/RedisStore.cs
  modules/evaluation-server/src/Streaming/DependencyInjection/StreamingBuilderExtensions.cs
  modules/evaluation-server/tests/Application.IntegrationTests/TestApp.cs
Labels: enhancement, evalution-server

#518 📖 doc: fix readme typo
  README.md
Labels: documentation, contribution, points:4

#517 📖 doc: add commercial license key statements
  README.md
Labels: documentation

#519 🧹 refactor: replace AnyAsync with CountAsync
  modules/back-end/src/Infrastructure/Bases/MongoDbService.cs
  modules/back-end/src/Infrastructure/Environments/EnvironmentService.cs
  modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs
  modules/back-end/src/Infrastructure/Groups/GroupService.cs
  modules/back-end/src/Infrastructure/Members/MemberService.cs
  modules/back-end/src/Infrastructure/Projects/ProjectService.cs
Labels: enhancement

#521 📖 doc: update Development.md
  .github/ISSUE_TEMPLATE/contribution-task.md
  Development.md
Labels: documentation

#528 ✨ feat: support asterisk in license feature list
  modules/back-end/src/Domain/Organizations/License.cs
  modules/back-end/src/Domain/Organizations/LicenseFeatures.cs
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: ui, api

#527 🐛 fix: trigger not pushing updates
  modules/back-end/src/Application/Triggers/RunTrigger.cs
Labels: bug

#529 🧹 refactor: change the way audit logs are written
  modules/back-end/src/Application/AuditLogs/GetAuditLogList.cs
  modules/back-end/src/Application/Caches/ICacheService.cs
  modules/back-end/src/Application/FeatureFlags/ArchiveFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/DeleteFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/OnFeatureFlagChanged.cs
  modules/back-end/src/Application/FeatureFlags/OnFeatureFlagDeleted.cs
  modules/back-end/src/Application/FeatureFlags/PatchFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/RestoreFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/SetTags.cs
  modules/back-end/src/Application/FeatureFlags/ToggleFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
  modules/back-end/src/Application/FeatureFlags/UpdateTargeting.cs
  modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
  modules/back-end/src/Application/Segments/ArchiveSegment.cs
  modules/back-end/src/Application/Segments/CreateSegment.cs
  modules/back-end/src/Application/Segments/DeleteSegment.cs
  modules/back-end/src/Application/Segments/OnSegmentChange.cs
  modules/back-end/src/Application/Segments/OnSegmentDeleted.cs
  modules/back-end/src/Application/Segments/PatchSegment.cs
  modules/back-end/src/Application/Segments/RestoreSegment.cs
  modules/back-end/src/Application/Segments/UpdateSegment.cs
  modules/back-end/src/Application/Triggers/RunTrigger.cs
  modules/back-end/src/Domain/AuditLogs/AuditLog.cs
  modules/back-end/src/Domain/Triggers/Trigger.cs
  modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleWorker.cs
  modules/back-end/src/Infrastructure/Redis/RedisCacheService.cs
Labels: refactoring
