Repository featbit/featbit, pull requests merged in 2023-08, with the labels that each got.

#470 🐛 Make Mongo Port configurable for DA-Server DB Liveness check
  modules/data-analytics/Dockerfile
  modules/data-analytics/docker-entrypoint.sh
Labels: da-server

#468 🧹 refactor: let user set redis url directly
  docker-compose-dev.yml
  docker-compose-partial.yml
  docker-compose-pro-dev.yml
  docker-compose-pro.yml
  docker-compose.yml
  kubernetes/pro/application/da-server-deployment.yaml
  kubernetes/standard/application/da-server-deployment.yaml
  modules/data-analytics/Dockerfile
  modules/data-analytics/app/__init__.py
  modules/data-analytics/app/setting.py
Labels: enhancement, da-server, breaking-change

#472 🏗 infra: build ui-api-bundle image
  .dockerignore
  docker/ui-api-bundle/Dockerfile
  docker/ui-api-bundle/README.md
  docker/ui-api-bundle/docker-compose-dev.yml
  docker/ui-api-bundle/nginx.conf
  docker/ui-api-bundle/services.d/api/run
  docker/ui-api-bundle/services.d/nginx/run
  dockerignore-test.sh
  modules/data-analytics/Dockerfile
Labels: infrastructure

#466 🧹 refactor: ngModelChange usages
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.ts
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
  modules/front-end/src/app/core/components/member-drawer/member-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.html
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.html
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.ts
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.ts
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.html
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, angular

#475 📖 doc: update contributors
  README.md
Labels: documentation

#476 🏗 infra: remove zookeeper
  docker-compose-infra.yml
  docker-compose-pro-dev.yml
  docker-compose-pro.yml
  infra/clickhouse/single_node/config.xml
  kubernetes/pro/Readme.md
  kubernetes/pro/cleanupInfrastructure.ps1
  kubernetes/pro/deployInfrastructure.ps1
  kubernetes/pro/infrastructure/clickhouse-configmap-etc.yaml
  kubernetes/pro/infrastructure/clickhouse-server-pod.yaml
  kubernetes/pro/infrastructure/clickhouse-server-service.yaml
  kubernetes/pro/infrastructure/kafka-pod.yaml
  kubernetes/pro/infrastructure/zookeeper-persistentvolumeclaim.yaml
  kubernetes/pro/infrastructure/zookeeper-pod.yaml
  kubernetes/pro/infrastructure/zookeeper-service.yaml
  kubernetes/pro/infrastructure/zookeeper-zoo-configmap.yaml
  modules/data-analytics/Readme.md
Labels: breaking-change, infrastructure

#479 🧹 refactor: move compose files to docker folder
  docker/composes/README.md
  docker/composes/docker-compose-clickhouse.yml
  docker/composes/docker-compose-dev.yml
  docker/composes/docker-compose-infra.yml
  docker/composes/docker-compose-pro-dev.yml
  docker/composes/docker-compose-services.yml
Labels: refactoring

#480 🐛 fix: update rule condition value didn't generate flag instructions
  modules/back-end/src/Domain/SemanticPatch/FlagComparer.cs
Labels: bug, api

#481 🐛 fix variation rollout compare bug
  modules/back-end/src/Domain/SemanticPatch/FlagComparer.cs
Labels: bug, api

#483 ✨ feat: enable separate producer and consumer kafka clusters
  docker/composes/README.md
  docker/composes/docker-compose-pro-dev-HA-kafka.yml
  modules/back-end/README.md
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/data-analytics/Readme.md
  modules/evaluation-server/README.md
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
Labels: enhancement

#484 ✨ feat: implement segment comparer
  modules/back-end/src/Application/Segments/CreateSegment.cs
  modules/back-end/src/Application/Segments/UpdateSegment.cs
  modules/back-end/src/Domain/Segments/Segment.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Models.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.Basic.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.Rule.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.RuleCondition.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.TargetUser.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Segment.cs
  modules/back-end/src/Domain/SemanticPatch/SegmentComparer.cs
  modules/back-end/src/Domain/SemanticPatch/SegmentInstructionKind.cs
Labels: api
