Repository featbit/featbit, pull requests merged in 2023-02, with the labels that each got.

#229 📖 Added official website links to the readme
  README.md
Labels: documentation

#231 🏗 infra: change the docker network name
  docker-compose.yml
Labels: enhancement

#239 🖍 Added padding to segment ref counter button
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.less
Labels: UI

#242 🐛fixed evaluation-server tests
  modules/evaluation-server/src/Infrastructure/Fakes/FakeCachePopulatingService.cs
  modules/evaluation-server/src/Infrastructure/Fakes/flags.json
  modules/evaluation-server/tests/Application.IntegrationTests/Initialization.cs
  modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoClientDataSyncAsync.verified.txt
  modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoServerDataSyncAsync.verified.txt
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/DataSyncTests.cs
  modules/evaluation-server/tests/TestBase/TestBase.csproj
Labels: Evaluation Server

#244 🏗 Added github workflow to log contributions
  .github/workflows/contribution.yml
Labels: enhancement

#232 🧹 Benchmark testing
  .gitignore
  benchmark/k6-scripts/k6-reporter.js
  benchmark/k6-scripts/k6-smoke-test.js
  benchmark/k6-scripts/plan.js
  benchmark/k6-scripts/test-results/result_extractor.js
  benchmark/k6-scripts/utils.js
  modules/evaluation-server/src/Domain/Core/DispatchAlgorithm.cs
  modules/evaluation-server/src/Infrastructure/Fakes/FakeCache.cs
  modules/evaluation-server/src/Infrastructure/Fakes/FakeCachePopulatingService.cs
  modules/evaluation-server/src/Infrastructure/Fakes/FakeCacheService.cs
  modules/evaluation-server/src/Infrastructure/Fakes/flags.json
  modules/evaluation-server/src/Infrastructure/Fakes/segments.json
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoClientDataSyncAsync.verified.txt
  modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoServerDataSyncAsync.verified.txt
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/DataSyncTests.cs
Labels: points:4

#143 🧹api test refactoring
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityApp.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/SmokeTests.cs
  modules/back-end/tests/Application.IntegrationTests/TestApp.cs
  modules/back-end/tests/Application.IntegrationTests/TestAppCollection.cs
  modules/back-end/tests/Application.IntegrationTests/Users/UserApp.cs
  modules/back-end/tests/Application.IntegrationTests/Users/UserControllerTests.cs
Labels: enhancement
