Repository featbit/featbit, pull requests merged in 2023-09, with the labels that each got.

#485 ✨ feat: add feature flag to control whether to enable schedule
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/change-review/change-review.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/environments/environment.prod.ts
  modules/front-end/src/environments/environment.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#487 🐛 fix: auditlog parse json error
  modules/front-end/src/app/core/components/audit-log/audit-log.component.html
  modules/front-end/src/app/core/components/change-list/change-list.component.ts
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html
Labels: bug, ui

#489 ✨ feat: allow user to remove a pending flag schedule
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Application/FeatureFlags/DeleteFlagSchedule.cs
  modules/back-end/src/Application/Services/IFlagScheduleService.cs
  modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleService.cs
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.less
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/environments/environment.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, api

#490 🐛 fix: organization undefined bug when the database is restored
  modules/front-end/src/app/core/guards/auth.guard.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#492 📖 doc: update environment variables
  docker-compose-pro.yml
  docker-compose.yml
  modules/back-end/README.md
  modules/data-analytics/Readme.md
  modules/evaluation-server/README.md
Labels: documentation

#486 ✨ feat: OIDC SSO integration
  docker/composes/README.md
  docker/experiment/docker-compose.yml
  docker/experiment/nginx/nginx.conf
  docker/https/README.md
  docker/https/certs/domain.ext
  docker/https/certs/localCA.crt
  docker/https/certs/localCA.key
  docker/https/certs/localCA.srl
  docker/https/certs/localServer.crt
  docker/https/certs/localServer.csr
  docker/https/certs/localServer.key
  docker/https/docker-compose-dev.yml
  docker/https/nginx.conf
  modules/back-end/src/Api/Authentication/OpenIdConnect/AuthParameters.cs
  modules/back-end/src/Api/Authentication/OpenIdConnect/ClientAuthenticator.cs
  modules/back-end/src/Api/Authentication/OpenIdConnect/OidcClient.cs
  modules/back-end/src/Api/Authentication/OpenIdConnect/OidcOptions.cs
  modules/back-end/src/Api/Authentication/ServiceCollectionExtensions.cs
  modules/back-end/src/Api/Controllers/SsoController.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Application/Identity/LoginByOidcCode.cs
  modules/back-end/src/Application/Organizations/AddUser.cs
  modules/back-end/src/Application/Services/IOrganizationService.cs
  modules/back-end/src/Domain/Users/User.cs
  modules/back-end/src/Infrastructure/Identity/IdentityService.cs
  modules/back-end/src/Infrastructure/Organizations/OrganizationService.cs
  modules/front-end/src/app/core/interceptors/request-response.interceptor.ts
  modules/front-end/src/app/core/services/identity.service.ts
  modules/front-end/src/app/core/services/sso.service.ts
  modules/front-end/src/app/features/login/do-login/do-login.component.html
  modules/front-end/src/app/features/login/do-login/do-login.component.ts
  modules/front-end/src/app/features/login/login.component.less
  modules/front-end/src/app/features/login/login.module.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement
