Repository featbit/featbit, pull requests merged in 2023-12, with the labels that each got.

#551 🖍 style: add space around flag name
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#556 ✨ feat: add timestamp filter when getting server side flags and segments
  modules/evaluation-server/src/Api/Public/SdkController.cs
Labels: evalution-server

#557 📖 doc: add environment variables for api and evaluation server
  modules/back-end/README.md
  modules/evaluation-server/README.md
Labels: documentation

#555 🏗 infra: replace REDIS_URL with REDIS_HOST, REDIS_PORT, REDIS_DB
  docker/composes/docker-compose-pro-dev-HA-kafka.yml
  docker/composes/docker-compose-pro-kafka-3-brokers-clickhouse-3-shards.yml
  docker/https/docker-compose-dev.yml
  docker/ui-api-bundle/docker-compose-dev.yml
  kubernetes/pro/application/da-server-deployment.yaml
  kubernetes/standard/application/da-server-deployment.yaml
  modules/data-analytics/README.md
  modules/data-analytics/Readme.md
Labels: infrastructure

#554 🐛 fix: broken links in get-started page
  modules/front-end/src/app/core/components/guide/guide.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#558 🖍 style: fix string input style
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
  modules/front-end/src/styles-common.less
  modules/front-end/src/styles/nz-input.less
  modules/front-end/src/styles/nz-select.less
Labels: ui

#559 ✨ feat: add instruction desctiptor
  modules/back-end/src/Domain/SemanticPatch/FlagComparer.cs
  modules/back-end/src/Domain/SemanticPatch/FlagInstructions.cs
  modules/back-end/src/Domain/SemanticPatch/Instruction.Flag.RuleCondition.cs
  modules/back-end/src/Domain/SemanticPatch/InstructionDescriptor.cs
  modules/front-end/src/app/core/components/pending-changes-drawer/data.ts
Labels: enhancement

#561 ✨ feat: allow live debugging a webhook
  modules/back-end/src/Api/Controllers/WebhookController.cs
  modules/back-end/src/Application/Services/IWebhookSender.cs
  modules/back-end/src/Application/Webhooks/SendWebhook.cs
  modules/back-end/src/Domain/Webhooks/WebhookRequest.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs
  modules/front-end/src/app/core/components/prism/prism.component.ts
  modules/front-end/src/app/core/components/test-webhook-modal/test-webhook-modal.component.html
  modules/front-end/src/app/core/components/test-webhook-modal/test-webhook-modal.component.less
  modules/front-end/src/app/core/components/test-webhook-modal/test-webhook-modal.component.ts
  modules/front-end/src/app/core/components/test-webhook-modal/test-webhook.ts
  modules/front-end/src/app/core/components/webhook-delivery/webhook-delivery.component.html
  modules/front-end/src/app/core/components/webhook-delivery/webhook-delivery.component.less
  modules/front-end/src/app/core/components/webhook-delivery/webhook-delivery.component.ts
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.html
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.less
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/handlebars.service.ts
  modules/front-end/src/app/core/services/monaco-service.ts
  modules/front-end/src/app/core/services/webhook.service.ts
  modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.html
  modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.html
  modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.less
  modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.ts
  modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.module.ts
  modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
  modules/front-end/src/app/shared/utils/form-validators.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/styles/nz-tabset.less
Labels: enhancement

#562 ✨ feat: webhook logs
  modules/back-end/src/Api/Controllers/WebhookController.cs
  modules/back-end/src/Application/Services/IWebhookService.cs
  modules/back-end/src/Application/Webhooks/GetWebhookDeliveryList.cs
  modules/back-end/src/Application/Webhooks/WebhookDeliveryFilter.cs
  modules/back-end/src/Infrastructure/AccessTokens/AccessTokenService.cs
  modules/back-end/src/Infrastructure/Policies/PolicyService.cs
  modules/back-end/src/Infrastructure/RelayProxies/RelayProxyService.cs
  modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs
  modules/back-end/src/Infrastructure/Webhooks/WebhookService.cs
  modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.html
  modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.less
  modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.ts
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/webhook.service.ts
  modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.html
  modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.ts
  modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/styles/icon.less
  modules/front-end/src/styles/nz-drawer.less
  modules/front-end/src/styles/nz-segmented.less
  modules/front-end/src/styles/standards.less
Labels: enhancement

#563 ✨ feat: add webhook change description
  modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
  modules/back-end/src/Domain/Webhooks/DataObjectBuilder.cs
  modules/front-end/src/app/core/components/test-webhook-modal/test-webhook.ts
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.html
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.less
  modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
Labels: enhancement

#566 🖍 style: show webhook delivery time with seconds
  modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.html
Labels: ui

#567 🐛 fix: inactive webhooks shouldn't be called
  modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
Labels: bug, api
