Repository featbit/featbit, pull requests merged in 2023-06, with the labels that each got.

#381 🚀Pro Manifest Improvements
  kubernetes/pro/application/api-server-deployment.yaml
  kubernetes/pro/application/da-server-deployment.yaml
  kubernetes/pro/application/evaluation-server-deployment.yaml
  kubernetes/pro/application/ui-deployment.yaml
  kubernetes/pro/cleanupInfrastructure.ps1
  kubernetes/pro/deployInfrastructure.ps1
  kubernetes/pro/infrastructure/kafka-pod.yaml
  kubernetes/pro/infrastructure/zookeeper-pod.yaml
  kubernetes/pro/infrastructure/zookeeper-zoo-configmap.yaml
Labels: enhancement, contribution, points:4

#389 ✨ feat: open segment APIs
  modules/back-end/src/Api/Authorization/Permissions.cs
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Api/Controllers/SegmentController.cs
  modules/back-end/src/Api/Swagger/Examples/PatchSegmentExamples.cs
  modules/back-end/src/Application/Bases/Models/PatchResult.cs
  modules/back-end/src/Application/FeatureFlags/PatchFeatureFlag.cs
  modules/back-end/src/Application/Segments/PatchSegment.cs
  modules/back-end/src/Domain/Resources/Resource.cs
  modules/back-end/src/Domain/Resources/ResourceHelper.cs
  modules/back-end/src/Domain/Resources/ResourceTypes.cs
  modules/back-end/src/Infrastructure/Resources/ResourceService.cs
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.ts
  modules/front-end/src/app/core/components/change-list/change-list.component.html
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement

#392 🐛 fix: incorrect status count in experiments dashboard
  modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
Labels: bug

#402 🐛 fix: experiment none type error
  modules/data-analytics/.vscode/settings.json
  modules/data-analytics/app/experimentation/models/experiment/trends_experiment_result.py
  modules/data-analytics/app/mongodb/db.py
  modules/data-analytics/utils/__init__.py
Labels: bug

#403 🧹 refactor: rename SDK endpoint and add event URL to SDK configs
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.html
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#405 🏗 infra: refactor UI Dockerfile
  modules/front-end/Dockerfile
  modules/front-end/docker-entrypoint.sh
Labels: ui

#406 🐛 fix: user can create duplicate key
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/IsFeatureFlagKeyUsed.cs
  modules/back-end/src/Application/Services/IFeatureFlagService.cs
  modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagService.cs
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
Labels: bug

#408 🐛 fix: refresh flag data when flag setting updated
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.ts
  modules/front-end/src/app/core/components/target-user/target-user.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/segments/types/segments-index.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#412 🐛 fix: calculate expt result error
  modules/data-analytics/app/experimentation/models/event/sql.py
  modules/data-analytics/app/experimentation/models/experiment/trends_experiment_result.py
  modules/evaluation-server/src/Domain/Insights/Insight.cs
Labels: bug

#414 ✨ feat: support variation name
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
  modules/back-end/src/Domain/FeatureFlags/Variation.cs
  modules/front-end/package-lock.json
  modules/front-end/package.json
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.less
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
  modules/front-end/src/app/core/components/find-rule/serve/rule-variation-value.pipe.ts
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.html
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/details.ts
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.less
  modules/front-end/src/app/shared/rules.ts
  modules/front-end/src/assets/icons/icon-plus.svg
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/variables.less
Labels: enhancement

#424 🖍 style: address styling issues on portal site
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: ui

#425 ✨ feat: display variation names instead of values in insights page
  modules/back-end/src/Application/FeatureFlags/GetInsights.cs
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.ts
Labels: ui
