Repository featbit/featbit, pull requests merged in 2023-11, with the labels that each got.

#523 ✨ feat: flag change request
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Application/FeatureFlags/ApplyFlagChangeRequest.cs
  modules/back-end/src/Application/FeatureFlags/ApproveFlagChangeRequest.cs
  modules/back-end/src/Application/FeatureFlags/CreateFlagChangeRequest.cs
  modules/back-end/src/Application/FeatureFlags/CreateFlagSchedule.cs
  modules/back-end/src/Application/FeatureFlags/DeclineFlagChangeRequest.cs
  modules/back-end/src/Application/FeatureFlags/DeleteFlagChangeRequest.cs
  modules/back-end/src/Application/FeatureFlags/DeleteFlagSchedule.cs
  modules/back-end/src/Application/FeatureFlags/GetPendingChanges.cs
  modules/back-end/src/Application/FeatureFlags/GetPendingChangesList.cs
  modules/back-end/src/Application/FeatureFlags/PendingChangeType.cs
  modules/back-end/src/Application/FeatureFlags/PendingChangesVm.cs
  modules/back-end/src/Application/FeatureFlags/UpdateTargeting.cs
  modules/back-end/src/Application/Services/IFeatureFlagAppService.cs
  modules/back-end/src/Application/Services/IFlagChangeRequestService.cs
  modules/back-end/src/Domain/AuditLogs/Operations.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
  modules/back-end/src/Domain/FeatureFlags/FlagTargeting.cs
  modules/back-end/src/Domain/FlagChangeRequests/FlagChangeRequest.cs
  modules/back-end/src/Domain/FlagChangeRequests/FlagChangeRequestAction.cs
  modules/back-end/src/Domain/FlagChangeRequests/FlagChangeRequestStatus.cs
  modules/back-end/src/Domain/FlagChangeRequests/Reviewer.cs
  modules/back-end/src/Domain/FlagDrafts/FlagDraft.cs
  modules/back-end/src/Domain/FlagSchedules/FlagSchedule.cs
  modules/back-end/src/Domain/FlagSchedules/FlagScheduleStatus.cs
  modules/back-end/src/Domain/Organizations/LicenseFeatures.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/FeatureFlags/FeatureFlagAppService.cs
  modules/back-end/src/Infrastructure/FlagChangeRequests/FlagChangeRequestService.cs
  modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleService.cs
  modules/back-end/src/Infrastructure/FlagSchedules/FlagScheduleWorker.cs
  modules/back-end/src/Infrastructure/MongoDb/MongoDbClient.cs
  modules/front-end/src/app/core/components/audit-log/audit-log.component.ts
  modules/front-end/src/app/core/components/audit-log/types.ts
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/change-review/change-review.component.less
  modules/front-end/src/app/core/components/change-review/change-review.component.ts
  modules/front-end/src/app/core/components/change-review/types.ts
  modules/front-end/src/app/core/components/license/license.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.less
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.ts
  modules/front-end/src/app/core/components/pending-changes-drawer/types.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: ui, api

#532 🖍 style: extend length of selection item content of nz-select component
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
Labels: ui

#538 🐛 fix: auto offset store should be disabled by default
  modules/back-end/src/Api/appsettings.Development.json
  modules/back-end/src/Api/appsettings.json
  modules/back-end/tests/Application.IntegrationTests/Snapshots/KafkaConfigTests.DefaultProducerConsumerConfig.verified.txt
  modules/evaluation-server/src/Api/appsettings.Development.json
  modules/evaluation-server/src/Api/appsettings.json
Labels: bug

#535 ✨ feat: add discrete health checks to da-server
  modules/data-analytics/app/__init__.py
  modules/data-analytics/app/health/__init__.py
  modules/data-analytics/app/health/views.py
Labels: enhancement, da-server

#526 🧹 refactor: ab testing refactoring and improvements
  modules/back-end/src/Application/Experiments/CreateExperiment.cs
  modules/back-end/src/Application/Experiments/ExperimentVm.cs
  modules/back-end/src/Application/Experiments/GetExperimentIterationResults.cs
  modules/back-end/src/Domain/Experiments/Experiment.cs
  modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
  modules/back-end/src/Infrastructure/Experiments/OlapService.cs
  modules/data-analytics/Dockerfile
  modules/data-analytics/app/commands.py
  modules/data-analytics/app/experimentation/models/event/sql.py
  modules/data-analytics/app/experimentation/models/experiment/experiment_types.py
  modules/data-analytics/app/experimentation/models/experiment/trends_experiment_result.py
  modules/data-analytics/app/experimentation/views.py
  modules/data-analytics/app/mongodb/models/event/util.py
  modules/data-analytics/utils/__init__.py
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
  modules/front-end/src/app/core/components/menu/menu.component.less
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.less
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/features/safe/experiments/types.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement

#541 🧹 refactor: code clean and style fixes
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.ts
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.less
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: refactoring

#530 🧹 refactor: rename account to organization
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
  kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
  modules/back-end/src/Domain/Resources/Resource.cs
  modules/back-end/src/Domain/Resources/ResourceTypes.cs
  modules/back-end/src/Infrastructure/Groups/GroupService.cs
  modules/back-end/src/Infrastructure/Resources/ResourceService.cs
  modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.ts
  modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.spec.ts
  modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.ts
  modules/front-end/src/app/core/services/identity.service.ts
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/core/translations/resource.translation.ts
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.html
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.ts
  modules/front-end/src/app/features/safe/organizations/organizations.component.spec.ts
  modules/front-end/src/app/features/safe/organizations/organizations.component.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, api, breaking-change

#543 🖍 style: unify nz-select style
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
  modules/front-end/src/app/core/components/audit-logs/audit-logs.component.html
  modules/front-end/src/app/core/components/change-review/change-review.component.html
  modules/front-end/src/app/core/components/experiment-drawer/experiment-drawer.component.html
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.less
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.html
  modules/front-end/src/app/core/components/find-rule/serve/serve.component.less
  modules/front-end/src/app/core/components/member-drawer/member-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.html
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.less
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.html
  modules/front-end/src/app/core/components/target-user/target-user.component.html
  modules/front-end/src/app/features/login/login.component.less
  modules/front-end/src/app/features/safe/end-users/index/index.component.html
  modules/front-end/src/app/features/safe/end-users/index/index.component.less
  modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.html
  modules/front-end/src/app/features/safe/experiments/metrics/metrics.component.ts
  modules/front-end/src/app/features/safe/experiments/types.ts
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.less
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.html
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
  modules/front-end/src/app/features/safe/iam/components/policy-editor/actions-selector/actions-selector.component.html
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.html
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.less
  modules/front-end/src/app/features/safe/iam/components/policy-editor/resources-selector/resources-selector.component.html
  modules/front-end/src/app/features/safe/iam/groups/details/policies/policies.component.html
  modules/front-end/src/app/features/safe/iam/groups/details/policies/policies.component.less
  modules/front-end/src/app/features/safe/iam/groups/details/team/team.component.html
  modules/front-end/src/app/features/safe/iam/groups/details/team/team.component.less
  modules/front-end/src/app/features/safe/iam/policies/details/groups/groups.component.html
  modules/front-end/src/app/features/safe/iam/policies/details/groups/groups.component.less
  modules/front-end/src/app/features/safe/iam/policies/details/team/team.component.html
  modules/front-end/src/app/features/safe/iam/policies/details/team/team.component.less
  modules/front-end/src/app/features/safe/iam/team/details/direct-policies/direct-policies.component.html
  modules/front-end/src/app/features/safe/iam/team/details/direct-policies/direct-policies.component.less
  modules/front-end/src/app/features/safe/iam/team/details/groups/groups.component.html
  modules/front-end/src/app/features/safe/iam/team/details/groups/groups.component.less
  modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.html
  modules/front-end/src/app/features/safe/safe.component.less
  modules/front-end/src/app/features/safe/workspaces/project/project.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/nz-select.less
  modules/front-end/src/styles-common.less
Labels: ui

#546 📖 doc: fix broken links in README.md
  README.md
Labels: documentation

#545 🏗 infra: support set redis password for services
  docker-compose-pro.yml
  docker-compose.yml
  docker/composes/docker-compose-dev.yml
  docker/composes/docker-compose-pro-dev.yml
  docker/composes/docker-compose-redis-cluster.yml
  docker/composes/docker-compose-redis-sentinel.yml
  docker/composes/docker-compose-services.yml
  modules/back-end/src/Api/appsettings.Development.json
  modules/back-end/src/Api/appsettings.json
  modules/back-end/src/Infrastructure/Redis/DefaultRedisClient.cs
  modules/data-analytics/Dockerfile
  modules/data-analytics/app/__init__.py
  modules/data-analytics/app/setting.py
  modules/evaluation-server/src/Api/appsettings.Development.json
  modules/evaluation-server/src/Api/appsettings.json
  modules/evaluation-server/src/Infrastructure/Redis/RedisClient.cs
  modules/evaluation-server/src/Infrastructure/Redis/RedisOptions.cs
Labels: breaking-change

#547 🏗 infra: build latest image only if github action runs from main branch
  .github/workflows/publish-docker-images.yml
Labels: infrastructure

#549 🏗 infra: refactor publish-docker-images.yml
  .github/workflows/publish-docker-images.yml
Labels: infrastructure
