Repository featbit/featbit, pull requests merged in 2023-05, with the labels that each got.

#345 🧹 refactor: Improve topic names for clarity and consistency
  docker-compose-pro-dev.yml
  docker-compose-pro.yml
  modules/back-end/src/Domain/Messages/Topics.cs
  modules/data-analytics/app/clickhouse/kafka/kafka_topics.py
  modules/evaluation-server/src/Domain/Core/Topics.cs
Labels: breaking-change

#346 🧹 refactor: make the access token drawer style consistent
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#354 Add Kubernetes Manifests for Featbit Standard
  kubernetes/standard/Readme.md
  kubernetes/standard/application/api-server-deployment.yaml
  kubernetes/standard/application/api-server-service.yaml
  kubernetes/standard/application/da-server-deployment.yaml
  kubernetes/standard/application/da-server-service.yaml
  kubernetes/standard/application/evaluation-server-deployment.yaml
  kubernetes/standard/application/evaluation-server-service.yaml
  kubernetes/standard/application/ui-deployment.yaml
  kubernetes/standard/application/ui-service.yaml
  kubernetes/standard/deployApplication.ps1
  kubernetes/standard/deployInfrastructure.ps1
  kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
  kubernetes/standard/infrastructure/mongodb-persistentvolumeclaim.yaml
  kubernetes/standard/infrastructure/mongodb-pod.yaml
  kubernetes/standard/infrastructure/mongodb-service.yaml
  kubernetes/standard/infrastructure/redis-persistentvolumeclaim.yaml
  kubernetes/standard/infrastructure/redis-pod.yaml
  kubernetes/standard/infrastructure/redis-service.yaml
  kubernetes/standard/ingress/traefik-ingress-api.yaml
  kubernetes/standard/ingress/traefik-ingress-evaluation-server.yaml
  kubernetes/standard/ingress/traefik-ingress-ui.yaml
Labels: contribution, points:12

#359 🔥 fix: data change not pushed to sdks
  modules/evaluation-server/src/Domain/Core/Topics.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/evaluation-server/src/Infrastructure/Redis/RedisMessageConsumer.cs
Labels: bug

#361 🐛 fix: cannot reset password
  modules/back-end/src/Application/Identity/ResetPassword.cs
  modules/front-end/src/app/features/safe/organizations/profile/profile.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug

#357 🧹 refactor: unify feature flag on/off confirm messages
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: points:4

#366 🐛 fix: env id cache
  modules/front-end/src/app/core/services/audit-log.service.ts
  modules/front-end/src/app/core/services/env-setting.service.ts
  modules/front-end/src/app/core/services/env-user-prop.service.ts
  modules/front-end/src/app/core/services/env-user.service.ts
  modules/front-end/src/app/core/services/env.service.ts
  modules/front-end/src/app/core/services/experiment.service.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/core/services/segment.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/safe.component.spec.ts
  modules/front-end/src/app/features/safe/segments/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/segments/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/segments/index/index.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug

#367 🐛 fix: use event-url & streaming-url on server-side SDKs' code snippets
  modules/front-end/src/app/core/components/prism/prism.component.ts
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug

#373 🐛 fix: make redoc available for production environment
  modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
Labels: bug, api, points:4

#369 Add Kubernetes Manifests for the Professional version of Featbit and the demo application
  kubernetes/demo/application/demo-dino-game-vue-deployment.yaml
  kubernetes/demo/application/demo-dino-game-vue-service.yaml
  kubernetes/demo/deployApplication.ps1
  kubernetes/demo/ingress/ingress-demo-dino-game-vue.yaml
  kubernetes/pro/Readme.md
  kubernetes/pro/application/api-server-deployment.yaml
  kubernetes/pro/application/api-server-service.yaml
  kubernetes/pro/application/da-server-deployment.yaml
  kubernetes/pro/application/da-server-service.yaml
  kubernetes/pro/application/evaluation-server-deployment.yaml
  kubernetes/pro/application/evaluation-server-service.yaml
  kubernetes/pro/application/ui-deployment.yaml
  kubernetes/pro/application/ui-service.yaml
  kubernetes/pro/deployApplication.ps1
  kubernetes/pro/deployInfrastructure.ps1
  kubernetes/pro/infrastructure/clickhouse-configmap-etc.yaml
  kubernetes/pro/infrastructure/clickhouse-server-persistentvolumeclaim.yaml
  kubernetes/pro/infrastructure/clickhouse-server-pod.yaml
  kubernetes/pro/infrastructure/clickhouse-server-service.yaml
  kubernetes/pro/infrastructure/kafka-persistentvolumeclaim.yaml
  kubernetes/pro/infrastructure/kafka-pod.yaml
  kubernetes/pro/infrastructure/kafka-service.yaml
  kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
  kubernetes/pro/infrastructure/mongodb-persistentvolumeclaim.yaml
  kubernetes/pro/infrastructure/mongodb-pod.yaml
  kubernetes/pro/infrastructure/mongodb-service.yaml
  kubernetes/pro/infrastructure/redis-persistentvolumeclaim.yaml
  kubernetes/pro/infrastructure/redis-pod.yaml
  kubernetes/pro/infrastructure/redis-service.yaml
  kubernetes/pro/infrastructure/zookeeper-persistentvolumeclaim.yaml
  kubernetes/pro/infrastructure/zookeeper-pod.yaml
  kubernetes/pro/infrastructure/zookeeper-service.yaml
  kubernetes/pro/ingress/traefik-ingress-api.yaml
  kubernetes/pro/ingress/traefik-ingress-evaluation-server.yaml
  kubernetes/pro/ingress/traefik-ingress-ui.yaml
Labels: points:24

#376 🐛 fix: get started module layout
  modules/front-end/src/app/core/components/guide/guide.component.html
  modules/front-end/src/app/core/components/prism/prism.theme.less
  modules/front-end/src/app/features/safe/get-started/get-started.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#375 🏗 infra: update api service definition
  docker-compose-dev.yml
  docker-compose-pro.yml
  kubernetes/pro/application/api-server-deployment.yaml
  kubernetes/pro/application/ui-deployment.yaml
Labels: enhancement

#378 🧹 refactor: replace `lodash` with `lodash-es`
  modules/front-end/package-lock.json
  modules/front-end/package.json
  modules/front-end/src/app/shared/diff/feature-flag.differ.ts
  modules/front-end/src/app/shared/diff/index.ts
  modules/front-end/src/app/shared/diff/segment.differ.ts
Labels: ui, points:4

#384 📖 doc: update README.md
  README.md
Labels: documentation

#382 🐛 fix: display complete information when hovering on variants (#356)
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, points:4
