Repository featbit/featbit, pull requests merged in 2023-04, with the labels that each got.

#316 ✨ feat: add LLM powered assistant module
  .gitignore
  llm/.gitignore
  llm/README.md
  llm/remove-feature-flags/chat-completion-cli.py
  llm/remove-feature-flags/fine-tune-backup/fine-tuning-model.md
  llm/remove-feature-flags/fine-tune-backup/gpt3-fine-tune-model.jsonl
Labels: enhancement

#317 ✨ feat: open more feature flag APIs
  modules/back-end/src/Api/Controllers/BasicController.cs
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Application/Bases/Models/PagedResult.cs
  modules/back-end/src/Application/FeatureFlags/FeatureFlagFilter.cs
  modules/back-end/src/Application/FeatureFlags/FeatureFlagVm.cs
Labels: enhancement

#319 🐛 fix: audit log and flag changes not written or published when patching update feature flag
  modules/back-end/src/Api/Authentication/OpenApiHandler.cs
  modules/back-end/src/Application/AuditLogs/GetAuditLogList.cs
  modules/back-end/src/Application/FeatureFlags/PatchFeatureFlag.cs
Labels: bug, API

#321 🧹 refactor: redis lpop usage
  modules/back-end/src/Infrastructure/Redis/RedisMessageConsumer.cs
Labels: enhancement

#324 📖 doc: add feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#325 📖 doc: add help wanted issue template
  .github/ISSUE_TEMPLATE/contribution-task.md
Labels: documentation

#328 fix typo on feature flag's experimentation page
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
Labels: points:4

#334 📖 doc: update Development.md and contribution task template
  .github/ISSUE_TEMPLATE/contribution-task.md
  Development.md
Labels: documentation

#336 🐛 fix: multi language support for experimentation iteration label
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, UI

#339 Changed EscapeRegex method's location, added a test and commented both.
  .gitignore
  modules/back-end/src/Domain/Resources/ResourceHelper.cs
  modules/back-end/src/Domain/Utils/StringHelper.cs
  modules/back-end/tests/Domain.UnitTests/Utils/StringHelperTests.cs
Labels: contribution

#340 🧹 refactor: updated "Feature flags and segments" label to more concise one
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.html
  modules/front-end/src/app/features/safe/end-users/index/index.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: points:4
