Repository featbit/featbit, pull requests merged in 2023-03, with the labels that each got.

#245 🏗 CI: added pr link to contribution excel file
  .github/workflows/contribution.yml
Labels: points:4

#246 🏗CI: trigger ui change validations only when the UI code is changed
  .github/workflows/ui-change-validations.yml
Labels: points:4

#248 🏗Fixed contributor name and added contributor profile
  .github/workflows/contribution.yml
Labels: points:4

#249 🧹 refactor evaluation server kafka usage
  modules/evaluation-server/src/Api/Public/InsightController.cs
  modules/evaluation-server/src/Api/ServicesRegister.cs
  modules/evaluation-server/src/Domain/Core/IMqMessageHandler.cs
  modules/evaluation-server/src/Domain/Core/IMqMessageProducer.cs
  modules/evaluation-server/src/Domain/WebSockets/ConnectionHandler.Log.cs
  modules/evaluation-server/src/Infrastructure/Caches/CachePopulatingHostedService.cs
  modules/evaluation-server/src/Infrastructure/Fakes/FakeMessageProducer.cs
  modules/evaluation-server/src/Infrastructure/Kafka/IKafkaMessageHandler.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.Log.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageProducer.Log.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageProducer.cs
  modules/evaluation-server/src/Infrastructure/MqMessageHandlers/FeatureFlagChangeMessageHandler.cs
  modules/evaluation-server/src/Infrastructure/MqMessageHandlers/SegmentChangeMessageHandler.cs
  modules/evaluation-server/src/Infrastructure/WsMessageHandlers/DataSyncMessageHandler.cs
Labels: Evaluation Server, points:4

#251 📖 Readme Typo fix
  README.md
Labels: documentation

#250 📖 Add benchmark readme
  benchmark/README.md
  benchmark/k6-scripts/test-results/result_extractor.js
Labels: documentation, points:4

#253 🐛 fix: fixed copy not working bug in a non secure context
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/iam/groups/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/iam/groups/index/index.component.ts
  modules/front-end/src/app/features/safe/iam/policies/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/iam/policies/index/index.component.ts
  modules/front-end/src/app/features/safe/iam/team/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/iam/team/index/index.component.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/app/shared/utils/index.ts
Labels: UI, points:4

#256 🏗 Create contribution task issue template
  .github/ISSUE_TEMPLATE/contribution_task.md
Labels: points:4

#254 🐛 fix: the flag change message was not pushed to the client sdk
  docker-compose-dev.yml
  docker-compose.yml
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/HostedServices/KafkaConsumerService.Log.cs
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.Log.cs
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageProducer.Log.cs
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageProducer.cs
  modules/back-end/tests/Application.IntegrationTests/TestApp.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
Labels: points:8

#258 ✨ feat: (api) add feature flag description
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/FeatureFlagVm.cs
  modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
Labels: API, points:4

#259 ✨ Add description field to new feature form
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, points:4

#263 📖 doc: update contribution task template
  .github/ISSUE_TEMPLATE/contribution_task.md
  Development.md
  README.md
Labels: documentation

#264 Added missing translations
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#267 ✨feat: added a tooltip for trigger url to tell how to invoke a trigger
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.less
Labels: UI

#269 🧹refactor iam
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  modules/back-end/src/Application/Resources/ResourceVm.cs
  modules/back-end/src/Domain/Resources/Resource.cs
  modules/back-end/src/Domain/Resources/ResourceType.cs
  modules/back-end/src/Infrastructure/Resources/ResourceService.cs
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/core/services/policy.service.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/resources-selector/resources-selector.component.ts
  modules/front-end/src/app/features/safe/iam/policies/details/permission/permission.component.ts
  modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/app/shared/permissions.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, API

#270 ✨ feat: added description field to feature flag setting page
  modules/front-end/src/app/features/safe/experiments/overview/overview.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/details.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/policy-editor.component.less
  modules/front-end/src/app/features/safe/iam/groups/index/index.component.less
  modules/front-end/src/app/features/safe/iam/policies/index/index.component.less
  modules/front-end/src/app/features/safe/iam/team/index/index.component.less
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/variables.less
Labels: UI

#271 ✨ feat: implemented a feature to allow users to send feedback to featbit maintainer
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/services/feedback.service.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#272 📖 fixed google sheet link
  .github/ISSUE_TEMPLATE/contribution_task.md
Labels: documentation

#282 ✨ feat: add environment key
  modules/back-end/src/Api/Controllers/EnvironmentController.cs
  modules/back-end/src/Application/Bases/ErrorCodes.cs
  modules/back-end/src/Application/EndUsers/GetFeatureFlagEndUserList.cs
  modules/back-end/src/Application/Environments/CreateEnvironment.cs
  modules/back-end/src/Application/Environments/IsKeyUsed.cs
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/GetInsights.cs
  modules/back-end/src/Domain/Environments/Environment.cs
  modules/back-end/src/Infrastructure/Projects/ProjectService.cs
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/app/core/components/header/header.component.less
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/services/env.service.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.less
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement, UI, API

#283 🐛 fix: api & evaluation-server shutdown errors
  modules/back-end/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaMessageConsumer.cs
Labels: enhancement

#284 🧹 Improved email validation error message
  modules/front-end/src/app/core/components/header/header.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#285 ✨ feat: implement permission based authorization for feature flag
  modules/back-end/src/Api/Authentication/AuthenticationBuilderExtensions.cs
  modules/back-end/src/Api/Authentication/OpenApiConstants.cs
  modules/back-end/src/Api/Authentication/OpenApiHandler.cs
  modules/back-end/src/Api/Authentication/OpenApiOptions.cs
  modules/back-end/src/Api/Authentication/Schemes.cs
  modules/back-end/src/Api/Authorization/ApiAuthorizationResultHandler.cs
  modules/back-end/src/Api/Authorization/DefaultPermissionChecker.cs
  modules/back-end/src/Api/Authorization/IPermissionChecker.cs
  modules/back-end/src/Api/Authorization/PermissionRequirement.cs
  modules/back-end/src/Api/Authorization/PermissionRequirementHandler.cs
  modules/back-end/src/Api/Authorization/Permissions.cs
  modules/back-end/src/Api/Controllers/ApiControllerBase.cs
  modules/back-end/src/Api/Controllers/BasicController.cs
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Api/Filters/VerifyOpenApiApplicableAttribute.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Domain/Resources/EffectType.cs
  modules/back-end/src/Domain/Resources/Resource.cs
  modules/back-end/src/Domain/Resources/ResourceHelper.cs
  modules/back-end/src/Domain/Resources/ResourceTypes.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Resources/ResourceService.cs
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.AllowAnonymous.verified.txt
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.ts
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/permission-check/permission-check.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
  modules/front-end/src/app/core/directives/permission-check.directive.ts
  modules/front-end/src/app/core/guards/accessTokens.guard.ts
  modules/front-end/src/app/core/guards/iam.guard.ts
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/core/translations/resource.translation.ts
  modules/front-end/src/app/features/safe/iam/components/policy-editor/resources-selector/resources-selector.component.html
  modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.ts
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, API

#275 ✨ feat: add api to retrieve the latest data for the server and client sdks
  modules/evaluation-server/src/Api/Public/SdkController.cs
  modules/evaluation-server/src/Domain/Services/IDataSyncService.cs
  modules/evaluation-server/src/Infrastructure/Services/DataSyncService.cs
Labels: API

#304 🧹 Regenerate translations
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI

#305 📖 Added step to contribution task template
  .github/ISSUE_TEMPLATE/contribution_task.md
Labels: documentation

#289 ✨ feat: added orgId to request header
  modules/front-end/src/app/core/interceptors/request-response.interceptor.ts
Labels: UI

#308 📖 Doc: Add "FeatBit Early Hero" medal next to the contributor's activity icon
  README.md
Labels: points:4

#307 🧹 refactor: remove organization id from request url
  modules/back-end/src/Api/Authentication/OpenApiConstants.cs
  modules/back-end/src/Api/Authentication/OpenApiHandler.cs
  modules/back-end/src/Api/Controllers/AccessTokenController.cs
  modules/back-end/src/Api/Controllers/ApiControllerBase.cs
  modules/back-end/src/Api/Controllers/GroupController.cs
  modules/back-end/src/Api/Controllers/MemberController.cs
  modules/back-end/src/Api/Controllers/OrganizationController.cs
  modules/back-end/src/Api/Controllers/PolicyController.cs
  modules/back-end/src/Api/Controllers/ProjectController.cs
  modules/back-end/src/Api/Controllers/ResourceController.cs
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/app/core/components/member-drawer/member-drawer.component.ts
  modules/front-end/src/app/core/components/metric-drawer/metric-drawer.component.ts
  modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.ts
  modules/front-end/src/app/core/interceptors/request-response.interceptor.ts
  modules/front-end/src/app/core/services/access-token.service.ts
  modules/front-end/src/app/core/services/account-preject-env-resolver.service.ts
  modules/front-end/src/app/core/services/group.service.ts
  modules/front-end/src/app/core/services/member.service.ts
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/core/services/policy.service.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/app/core/services/resource.service.ts
  modules/front-end/src/app/core/services/team.service.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/app/features/safe/organizations/organization/organization.component.ts
  modules/front-end/src/app/features/safe/organizations/project/project.component.html
  modules/front-end/src/app/features/safe/organizations/project/project.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: UI, API

#309 🧹 refactor: replace id with key in feature flag urls
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Application/FeatureFlags/ArchiveFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/DeleteFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/RestoreFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/SetTags.cs
  modules/back-end/src/Application/FeatureFlags/ToggleFeatureFlag.cs
  modules/back-end/src/Application/FeatureFlags/UpdateSetting.cs
  modules/back-end/src/Application/FeatureFlags/UpdateTargeting.cs
  modules/back-end/src/Application/FeatureFlags/UpdateVariations.cs
  modules/front-end/src/app/core/components/expt-rules-drawer/expt-rules-drawer.component.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/setting/setting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/details.ts
Labels: UI, API

#310 ✨ feat: add OpenApi doc support
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Api/Authentication/OpenApiAttribute.cs
  modules/back-end/src/Api/Authentication/OpenApiConstants.cs
  modules/back-end/src/Api/Controllers/ApiControllerBase.cs
  modules/back-end/src/Api/Controllers/ApiResponse.cs
  modules/back-end/src/Api/Controllers/BasicController.cs
  modules/back-end/src/Api/Filters/VerifyOpenApiApplicableAttribute.cs
  modules/back-end/src/Api/Setup/ConfigSwaggerOptions.cs
  modules/back-end/src/Api/Setup/MiddlewaresRegister.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Application/Application.csproj
  modules/back-end/src/Domain/Domain.csproj
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.ModelBinding.verified.txt
Labels: API

#312 ✨ feat: support swagger request example
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Api/Setup/ConfigSwaggerOptions.cs
  modules/back-end/src/Api/Setup/ConfigureMvcOptions.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Api/Swagger/ConfigureSwaggerOptions.cs
  modules/back-end/src/Api/Swagger/Examples/PatchFeatureFlagExamples.cs
Labels: API
