Repository featbit/featbit, pull requests merged in 2024-04, with the labels that each got.

#623 🔧 deps: bump dependency versions
  modules/back-end/src/Api/appsettings.Development.json
  modules/back-end/src/Api/appsettings.json
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/src/Infrastructure/Redis/RedisMessageProducer.cs
  modules/back-end/tests/Application.UnitTests/Identity/IdentityServiceTests.cs
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
Labels: enhancement, breaking-change

#624 🖍 fix: select organization style
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.html
Labels: ui

#614 ✨ feat: add `variationId` and `sendToExperiment` field to get client feature flags API
  modules/evaluation-server/src/Api/Public/SdkController.cs
  modules/evaluation-server/src/Streaming/Protocol/ClientSdkPayload.cs
  modules/evaluation-server/tests/Application.IntegrationTests/Snapshots/DataSyncTests.DoClientDataSyncAsync.verified.txt
Labels: evalution-server

#627 ✨ feat: allow user to use Google and Github to login
  modules/back-end/src/Api/Authentication/OAuth/EmailExtractor.cs
  modules/back-end/src/Api/Authentication/OAuth/OAuthClient.cs
  modules/back-end/src/Api/Authentication/OAuth/OAuthProvider.cs
  modules/back-end/src/Api/Authentication/OAuth/OAuthProviders.cs
  modules/back-end/src/Api/Authentication/OpenIdConnect/OidcClient.cs
  modules/back-end/src/Api/Authentication/ServiceCollectionExtensions.cs
  modules/back-end/src/Api/Controllers/OrganizationController.cs
  modules/back-end/src/Api/Controllers/SocialController.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Application/Identity/LoginByOAuthCode.cs
  modules/back-end/src/Application/Identity/OAuthProviderVm.cs
  modules/back-end/src/Application/Organizations/CreateOrganization.cs
  modules/back-end/src/Application/Workspaces/CreateWorkspace.cs
  modules/back-end/src/Domain/Users/UserOrigin.cs
  modules/front-end/src/app/core/interceptors/request-response.interceptor.ts
  modules/front-end/src/app/core/services/social.service.ts
  modules/front-end/src/app/features/login/do-login/do-login.component.html
  modules/front-end/src/app/features/login/do-login/do-login.component.less
  modules/front-end/src/app/features/login/do-login/do-login.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/app/shared/utils/index.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui, api

#628 ✨ feat: add flag key regex validation
  modules/back-end/src/Application/FeatureFlags/CreateFeatureFlag.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement

#629 🧹 chore: ignore data inconsistent environment when populating secrets cache
  modules/back-end/src/Infrastructure/Redis/RedisPopulatingService.cs
Labels: api

#634 🖍 style: fix account menu style
  modules/front-end/src/app/core/components/locale-switcher/locale-switcher.component.less
  modules/front-end/src/app/core/components/menu/menu.component.html
  modules/front-end/src/app/core/components/menu/menu.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#633 🧹 chore: update social login hint
  modules/front-end/src/app/features/login/do-login/do-login.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#635 🧹 refactor: align get client feature flags API with streaming response format
  modules/evaluation-server/src/Api/Public/SdkController.cs
  modules/evaluation-server/src/Streaming/Protocol/ClientSdkPayload.cs
  modules/evaluation-server/src/Streaming/Protocol/ServerSdkPayload.cs
Labels: evalution-server, breaking-change
