Repository featbit/featbit, pull requests merged in 2024-12, with the labels that each got.

#687 🐛 fix: cannot do SSO login when there is no default workspace key
  modules/front-end/src/app/features/login/do-login/do-login.component.ts
Labels: bug, ui

#688 ✨Sort Projects Alphabetically in Project/Env Modal
  modules/front-end/src/app/core/services/project.service.ts
Labels: contribution, angular

#685 🐛 fix: end user insight search not working
  modules/data-analytics/app/main/models/statistics/end_user/end_user_statistics.py
  modules/front-end/src/app/features/safe/feature-flags/details/insights/types.ts
Labels: bug, ui, da-server, points:8

#689 ✨ feat: add key to organization
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  modules/back-end/src/Api/Controllers/OrganizationController.cs
  modules/back-end/src/Application/Organizations/CreateOrganization.cs
  modules/back-end/src/Application/Organizations/IsKeyUsed.cs
  modules/back-end/src/Application/Organizations/Onboarding.cs
  modules/back-end/src/Application/Organizations/OrganizationVm.cs
  modules/back-end/src/Application/Services/IOrganizationService.cs
  modules/back-end/src/Application/Workspaces/CreateWorkspace.cs
  modules/back-end/src/Domain/Organizations/Organization.cs
  modules/back-end/src/Infrastructure/Organizations/OrganizationService.cs
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
  modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.html
  modules/front-end/src/app/core/components/organization-drawer/organization-drawer.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.html
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.html
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.ts
  modules/front-end/src/app/features/safe/workspaces/project/project.component.html
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement, breaking-change
