Repository featbit/featbit, pull requests merged in 2024-09, with the labels that each got.

#658 🔧 refactor: upgrade evaluation server to .NET 8
  modules/evaluation-server/deploy/Dockerfile
  modules/evaluation-server/global.json
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Api/Public/PublicApiControllerBase.cs
  modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
  modules/evaluation-server/src/Directory.Build.props
  modules/evaluation-server/src/Domain/Domain.csproj
  modules/evaluation-server/src/Domain/Shared/Secret.cs
  modules/evaluation-server/src/Infrastructure/ConfigurationExtensions.cs
  modules/evaluation-server/src/Infrastructure/HealthCheckBuilderExtensions.cs
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/src/Infrastructure/Kafka/KafkaHealthCheckBuilderExtensions.cs
  modules/evaluation-server/src/Streaming/Connections/Connection.cs
  modules/evaluation-server/src/Streaming/Connections/ConnectionType.cs
  modules/evaluation-server/src/Streaming/Connections/ConnectionVersion.cs
  modules/evaluation-server/src/Streaming/Connections/IRequestValidator.cs
  modules/evaluation-server/src/Streaming/Connections/RequestValidator.cs
  modules/evaluation-server/src/Streaming/Streaming.csproj
  modules/evaluation-server/src/Streaming/StreamingMiddleware.cs
  modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
  modules/evaluation-server/tests/Streaming.UnitTests/Streaming.UnitTests.csproj
Labels: contribution

#659 🔧 refactor: upgrade api server to .NET 8
  modules/back-end/deploy/Dockerfile
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Api/Authentication/OpenApiHandler.cs
  modules/back-end/src/Api/Program.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Application/Application.csproj
  modules/back-end/src/Application/Bases/Behaviours/ValidationBehaviour.cs
  modules/back-end/src/Application/ConfigureServices.cs
  modules/back-end/src/Domain/Domain.csproj
  modules/back-end/src/Infrastructure/ConfigurationExtensions.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/HealthCheckBuilderExtensions.cs
  modules/back-end/src/Infrastructure/Identity/IdentityService.cs
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/src/Infrastructure/Kafka/KafkaHealthCheckBuilderExtensions.cs
  modules/back-end/src/Infrastructure/MongoDb/MongoDbClient.cs
  modules/back-end/src/Infrastructure/Redis/DefaultRedisClient.cs
  modules/back-end/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/back-end/tests/Application.IntegrationTests/Basics/BasicControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Configuration/KafkaConfigTests.cs
  modules/back-end/tests/Application.IntegrationTests/Identity/IdentityControllerTests.cs
  modules/back-end/tests/Application.IntegrationTests/Initialization.cs
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.AllowAnonymous.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.ApiVersioning.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.Authorized.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.HandleException.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.ModelBinding.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.NeedAuthentication.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/BasicControllerTests.NeedLicense.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/IdentityControllerTests.LoginByEmail_RequestValidation.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/IdentityControllerTests.LoginByEmail_Success.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/IdentityControllerTests.LoginByPassword_RequestValidation.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/IdentityControllerTests.LoginByPassword_Success.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/KafkaConfigTests.DefaultProducerConsumerConfig.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/UserControllerTests.GetUserProfile.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Snapshots/UserControllerTests.GetUserProfile_NotExist.verified.txt
  modules/back-end/tests/Application.IntegrationTests/Users/UserControllerTests.cs
  modules/back-end/tests/Application.UnitTests/Application.UnitTests.csproj
  modules/back-end/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/back-end/tests/TestBase/TestBase.csproj
Labels: contribution

#661 🔧 refactor: bump evaluation server package versions
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Api/Program.cs
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/evaluation-server/tests/Application.IntegrationTests/WebSockets/DataSyncTests.cs
  modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
  modules/evaluation-server/tests/Streaming.UnitTests/Connections/ConnectionTypeTests.cs
  modules/evaluation-server/tests/Streaming.UnitTests/Shared/SecretTests.cs
  modules/evaluation-server/tests/Streaming.UnitTests/Shared/TokenNumberTests.cs
  modules/evaluation-server/tests/Streaming.UnitTests/Shared/TokenTests.cs
  modules/evaluation-server/tests/Streaming.UnitTests/Streaming.UnitTests.csproj
  modules/evaluation-server/tests/TestBase/TestBase.csproj
Labels: evalution-server, dependencies

#662 🔧 refactor: upgrade otel integration
  docker/composes/docker-compose-dev.yml
  docker/composes/docker-compose-otel-collector-contrib.yml
  docker/composes/docker-compose-otel.yml
  infra/otel/otel-collector-config.yml
  modules/back-end/deploy/Dockerfile
  modules/data-analytics/flasky.py
  modules/evaluation-server/deploy/Dockerfile
  modules/front-end/Dockerfile
Labels: dependencies

#663 🏗 infra: .NET auto instrumentation now support ARM64
  modules/back-end/deploy/Dockerfile
  modules/back-end/start.sh
  modules/evaluation-server/deploy/Dockerfile
  modules/evaluation-server/start.sh
Labels: infrastructure

#664 🏗 fix: multi platform dotnet project docker build hangs
  modules/back-end/Directory.Build.props
  modules/back-end/deploy/Dockerfile
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Application/Application.csproj
  modules/back-end/src/Domain/Domain.csproj
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/back-end/tests/Application.UnitTests/Application.UnitTests.csproj
  modules/back-end/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/back-end/tests/TestBase/TestBase.csproj
  modules/evaluation-server/Directory.Build.props
  modules/evaluation-server/deploy/Dockerfile
  modules/evaluation-server/global.json
  modules/evaluation-server/perf/Benchmarks/Benchmarks.csproj
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Directory.Build.props
  modules/evaluation-server/src/Domain/Domain.csproj
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/src/Streaming/Streaming.csproj
  modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
  modules/evaluation-server/tests/Streaming.UnitTests/Streaming.UnitTests.csproj
  modules/evaluation-server/tests/TestBase/InMemoryFakeLogger.cs
  modules/evaluation-server/tests/TestBase/TestBase.csproj
Labels: infrastructure

#666 🏗 fix: github action build and publish workflow
  .github/workflows/api-server-validations.yml
  .github/workflows/build-and-test-api.yml
  .github/workflows/build-and-test-els.yml
  .github/workflows/evaluation-server-validations.yml
  modules/back-end/deploy/Dockerfile
  modules/evaluation-server/deploy/Dockerfile
Labels: infrastructure

#669 🐛 fix: division by zero on numeric metrics
  modules/data-analytics/app/experimentation/models/experiment/experiment_types.py
Labels: bug

#670 ↩️ revert: revert wrong changes
  modules/back-end/Directory.Build.props
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Application/Application.csproj
  modules/back-end/src/Domain/Domain.csproj
  modules/back-end/src/Infrastructure/Infrastructure.csproj
  modules/back-end/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/back-end/tests/Application.UnitTests/Application.UnitTests.csproj
  modules/back-end/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/back-end/tests/TestBase/TestBase.csproj
  modules/back-end/tests/TestBase/TestLogger.cs
  modules/evaluation-server/Directory.Build.props
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Directory.Build.props
  modules/evaluation-server/src/Domain/Domain.csproj
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/src/Streaming/Streaming.csproj
  modules/evaluation-server/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
  modules/evaluation-server/tests/Domain.UnitTests/Domain.UnitTests.csproj
  modules/evaluation-server/tests/Infrastructure.UnitTests/Infrastructure.UnitTests.csproj
  modules/evaluation-server/tests/Streaming.UnitTests/Streaming.UnitTests.csproj
  modules/evaluation-server/tests/TestBase/TestBase.csproj
Labels: bug

#671 🏗 fix: arm64 build error
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Directory.Build.props
  modules/evaluation-server/src/Domain/Domain.csproj
  modules/evaluation-server/src/Infrastructure/Infrastructure.csproj
  modules/evaluation-server/src/Streaming/Streaming.csproj
Labels: infrastructure
