Repository featbit/featbit, pull requests merged in 2024-11, with the labels that each got.

#651 ✨ feat: fill variation values according to variation type
  modules/front-end/src/app/core/components/change-list/constants.ts
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.html
  modules/front-end/src/app/core/components/feature-flag-drawer/feature-flag-drawer.component.ts
  modules/front-end/src/app/features/safe/get-started/steps/create-feature-flag/create-feature-flag.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement, ui

#677 ✨ feat: allow retrieving projects using service token
  modules/back-end/src/Api/Authentication/OpenApiHandler.cs
  modules/back-end/src/Api/Authorization/Permissions.cs
  modules/back-end/src/Api/Controllers/ProjectController.cs
  modules/back-end/src/Api/Swagger/ConfigureSwaggerOptions.cs
  modules/back-end/src/Api/Swagger/OrganizationHeaderParameter.cs
  modules/back-end/src/Domain/Resources/ResourceHelper.cs
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement

#684 ✨ feat: allow to set default permissions for organization
  modules/back-end/src/Api/Controllers/OrganizationController.cs
  modules/back-end/src/Application/Organizations/AddUser.cs
  modules/back-end/src/Application/Organizations/GetOrganization.cs
  modules/back-end/src/Application/Organizations/OrganizationVm.cs
  modules/back-end/src/Application/Organizations/UpdateOrganization.cs
  modules/back-end/src/Application/Organizations/UpdateOrganizationName.cs
  modules/back-end/src/Domain/Organizations/Organization.cs
  modules/back-end/src/Domain/Organizations/OrganizationPermissions.cs
  modules/back-end/src/Infrastructure/MongoDb/ClassMaps.cs
  modules/back-end/src/Infrastructure/Organizations/OrganizationService.cs
  modules/front-end/src/app/core/services/organization.service.ts
  modules/front-end/src/app/features/safe/onboarding/steps/steps.component.ts
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.html
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.less
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.ts
  modules/front-end/src/app/shared/types.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement, ui, api

#681 ✨feat: optionally prevent empty webhook payloads
  modules/back-end/src/Application/Webhooks/CreateWebhook.cs
  modules/back-end/src/Application/Webhooks/SendWebhook.cs
  modules/back-end/src/Application/Webhooks/UpdateWebhook.cs
  modules/back-end/src/Application/Webhooks/WebhookBase.cs
  modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
  modules/back-end/src/Application/Webhooks/WebhookVm.cs
  modules/back-end/src/Domain/Utils/JsonExtensions.cs
  modules/back-end/src/Domain/Webhooks/Webhook.cs
  modules/back-end/src/Domain/Webhooks/WebhookDelivery.cs
  modules/back-end/src/Domain/Webhooks/WebhookRequest.cs
  modules/back-end/src/Infrastructure/Webhooks/WebhookSender.cs
  modules/front-end/src/app/core/components/test-webhook-modal/test-webhook-modal.component.ts
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.html
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.less
  modules/front-end/src/app/core/components/webhook-drawer/webhook-drawer.component.ts
  modules/front-end/src/app/features/safe/integrations/webhooks/webhooks.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement, ui, api
