Repository featbit/featbit, pull requests merged in 2024-02, with the labels that each got.

#584 ✨ feat: otel integration for backend services
  .gitignore
  docker/composes/docker-compose-otel-collector-contrib.yml
  docker/composes/docker-compose-otel.yml
  infra/otel/env/otel-api.env
  infra/otel/env/otel-das.env
  infra/otel/env/otel-els.env
  infra/otel/otel-collector-config.yml
  infra/otel/prometheus.yml
  infra/otel/utils/otel-env-vars.ps1
  modules/back-end/deploy/Dockerfile
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Api/Program.cs
  modules/data-analytics/Dockerfile
  modules/data-analytics/flasky.py
  modules/data-analytics/gunicorn.conf.py
  modules/data-analytics/requirements.txt
  modules/data-analytics/start.sh
  modules/evaluation-server/deploy/Dockerfile
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Api/Program.cs
Labels: enhancement

#588 🧹 refactor: unify otel configuration environment variables
  infra/otel/env/otel-api.env
  infra/otel/env/otel-das.env
  infra/otel/env/otel-els.env
  infra/otel/otel-collector-config.yml
  infra/otel/utils/otel-env-vars.ps1
  modules/back-end/src/Api/Api.csproj
  modules/data-analytics/gunicorn.conf.py
  modules/evaluation-server/src/Api/Api.csproj
Labels: breaking-change, refactoring

#589 📖 doc: add otel integration link
  README.md
Labels: documentation

#590 🐛 fix: serilog otel integration
  modules/back-end/src/Api/Program.cs
  modules/evaluation-server/src/Api/Program.cs
Labels: bug

#592 🐛 Fix date formatting in experimentation UI to conform with date-fns
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
Labels: ui

#593 🐛Fix date formatting in remote config UI to conform with date-fns
  modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
Labels: bug, ui

#583 🐛 Bugfix: When operation is selected, property cannot be selected.
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.ts
Labels: bug, ui

#601 🧹 refactor: restructure get `currentUserProp` method
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.ts
Labels: ui
