Repository featbit/featbit, pull requests merged in 2024-01, with the labels that each got.

#560 ✨ feat: added Node.js instructions to get started page
  modules/front-end/src/app/core/components/prism/prism.component.ts
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.html
  modules/front-end/src/app/features/safe/get-started/steps/connect-an-sdk/connect-an-sdk.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#569 🐛 fix: run webhook asynchronously
  modules/back-end/src/Application/FeatureFlags/OnFeatureFlagDeleted.cs
  modules/back-end/src/Application/Segments/OnSegmentDeleted.cs
Labels: bug

#575 🧹refactor(front-end): remove the commonJS warning of moment.js
  modules/front-end/package-lock.json
  modules/front-end/package.json
  modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
Labels: enhancement, ui, points:4

#578 🖍 CSS / Styling: Adjust the layout when choose "is one of" in "select operation"
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/styles/nz-select.less
Labels: enhancement, ui, points:8

#581 🐛 fix: broken links in UI
  modules/front-end/src/app/features/safe/feature-flags/details/targeting/targeting.component.html
Labels: ui

#553 ✨ Add Opentelemetry Auto-Instrumentation to Backend Services
  .gitignore
  docker/composes/docker-compose-dev.yml
  docker/composes/docker-compose-otel-collector-contrib.yml
  infra/otel/env/otel-api.env
  infra/otel/env/otel-das.env
  infra/otel/env/otel-els.env
  infra/otel/otel-collector-config.yml
  infra/otel/prometheus.yml
  infra/otel/utils/otel-env-vars.ps1
  modules/back-end/deploy/Dockerfile
  modules/back-end/src/Api/Api.csproj
  modules/back-end/src/Api/Program.cs
  modules/data-analytics/Dockerfile
  modules/data-analytics/app/__init__.py
  modules/data-analytics/flasky.py
  modules/data-analytics/gunicorn.conf.py
  modules/data-analytics/requirements.txt
  modules/data-analytics/start.sh
  modules/evaluation-server/deploy/Dockerfile
  modules/evaluation-server/src/Api/Api.csproj
  modules/evaluation-server/src/Api/Program.cs
Labels: enhancement

#585 🐛 fix: profile menu link
  modules/front-end/src/app/core/components/menu/menu.component.html
Labels: bug, ui
