Repository featbit/featbit, pull requests merged in 2024-10, with the labels that each got.

#673 🚀 perf: add mongodb indexes
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  kubernetes/pro/infrastructure/mongodb-init-configMap.yaml
  kubernetes/standard/infrastructure/mongodb-init-configMap.yaml
Labels: infrastructure

#675 🐛 fix: webhooks are not filtered by scope
  modules/back-end/src/Application/Webhooks/WebhookHandlers.cs
  modules/back-end/src/Domain/Environments/ResourceDescriptor.cs
Labels: bug, api

#676 🐛 fix: switching environment bug
  modules/front-end/src/app/core/components/header/header.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui
