Repository featbit/featbit, pull requests merged in 2024-05, with the labels that each got.

#638 🐛 fix: fixed date formatting bug
  modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
Labels: bug, ui

#639 🧹refactor: change hour format when displaying date
  modules/front-end/src/app/features/safe/data-sync/remote-sync/remote-sync.component.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#642 📖 doc: added react native sdk link to readme
  README.md
Labels: documentation

#643 🖍 fix: webhook events tooltip style
  modules/front-end/src/app/features/safe/integrations/webhooks/index/index.component.html
Labels: bug, ui

#644 🐛fix: experiment data lose bug
  modules/back-end/src/Api/Controllers/ExperimentController.cs
  modules/back-end/src/Application/Experiments/StartExperiment.cs
  modules/back-end/src/Application/Experiments/StartIteration.cs
  modules/back-end/src/Application/Experiments/StopExperiment.cs
  modules/back-end/src/Application/Experiments/StopIteration.cs
  modules/back-end/src/Application/Services/IExperimentService.cs
  modules/back-end/src/Domain/Experiments/Experiment.cs
  modules/back-end/src/Infrastructure/Experiments/ExperimentService.cs
  modules/front-end/src/app/core/services/experiment.service.ts
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.less
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug
