Repository featbit/featbit, pull requests merged in 2025-01, with the labels that each got.

#691 🧹 refactor: IAM use project and env key instead of name
  modules/back-end/src/Infrastructure/Resources/ResourceService.cs
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.html
  modules/front-end/src/app/core/components/env-drawer/env-drawer.component.ts
  modules/front-end/src/app/core/components/project-drawer/project-drawer.component.html
  modules/front-end/src/app/core/services/permissions.service.ts
  modules/front-end/src/app/features/safe/workspaces/project/project.component.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: enhancement, breaking-change

#692 🐛 fix: date display bug
  modules/front-end/src/app/core/components/audit-log/audit-log.component.html
  modules/front-end/src/app/core/components/license/license.component.html
  modules/front-end/src/app/core/components/license/license.component.ts
  modules/front-end/src/app/core/components/pending-changes-drawer/pending-changes-drawer.component.html
  modules/front-end/src/app/core/components/relay-proxy-drawer/relay-proxy-drawer.component.html
  modules/front-end/src/app/core/components/user-segments-flags-drawer/user-segments-flags-drawer.component.html
  modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.html
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/experimentation/experimentation.component.html
  modules/front-end/src/app/features/safe/feature-flags/details/insights/insights.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/integrations/access-tokens/index/index.component.html
  modules/front-end/src/app/features/safe/segments/index/index.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#693 📖 doc: add more advanced features
  README.md
Labels: documentation

#694 🐛 fix: license check bug
  modules/back-end/src/Api/Controllers/GlobalUserController.cs
  modules/back-end/src/Domain/Workspaces/LicenseFeatures.cs
  modules/front-end/src/app/shared/types.ts
Labels: bug

#696 ✨ feat: copy feature flag v2
  modules/back-end/src/Api/Controllers/FeatureFlagController.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheck.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheckResult.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnvResult.cs
  modules/back-end/src/Application/Segments/GetSegmentByIds.cs
  modules/back-end/src/Application/Services/ISegmentService.cs
  modules/back-end/src/Domain/FeatureFlags/FeatureFlag.cs
  modules/back-end/src/Domain/Resources/RN.cs
  modules/back-end/src/Infrastructure/Segments/SegmentService.cs
  modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.html
  modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.less
  modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.ts
  modules/front-end/src/app/core/components/segment-creation-modal/segment-creation-modal.component.html
  modules/front-end/src/app/core/core.module.ts
  modules/front-end/src/app/core/services/feature-flag.service.ts
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.html
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.less
  modules/front-end/src/app/features/safe/feature-flags/index/index.component.ts
  modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
  modules/front-end/src/styles-common.less
  modules/front-end/src/styles/nz-collapse.less
  modules/front-end/src/styles/nz-modal.less
Labels: enhancement, feature-request

#697 🖍 style: fix select segment style
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.html
  modules/front-end/src/app/core/components/find-rule/rule/rule.component.less
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#698 🔥fix: load current project environments only when copying feature flags
  modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.ts
  modules/front-end/src/app/core/services/project.service.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug
