Repository featbit/featbit, pull requests merged in 2025-09, with the labels that each got.

#768 🏗 Configure Dependabot for npm in front-end directory
  .github/dependabot.yml
Labels: ui

#792 🐛 fix: ng-zorro-antd breaking changes
  modules/evaluation-server/src/Directory.Build.props
  modules/front-end/src/app/core/components/access-token-drawer/access-token-drawer.component.html
  modules/front-end/src/app/core/components/guide/guide.component.html
  modules/front-end/src/app/core/components/segment-creation-modal/segment-creation-modal.component.ts
  modules/front-end/src/app/core/components/webhook-deliveries/webhook-deliveries.component.ts
  modules/front-end/src/app/features/safe/feature-flags/components/flag-triggers/flag-triggers.component.html
  modules/front-end/src/app/features/safe/get-started/steps/steps.component.html
  modules/front-end/src/app/features/safe/workspaces/project/project.component.html
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, ui

#763 🏗 infra: db migrations scripts for v5.1.0
  infra/mongodb/docker-entrypoint-initdb.d/v5.0.5.js
  infra/mongodb/docker-entrypoint-initdb.d/v5.1.0.js
  infra/postgresql/docker-entrypoint-initdb.d/v5.1.0.sql
Labels: infrastructure

#793 🐛 fix: da-server build error
  modules/data-analytics/Dockerfile
Labels: bug, da-server, infrastructure

#794 🏗 infra: update ui service base image
  modules/front-end/Dockerfile
Labels: bug, angular, infrastructure

#795 🐛 fix: incorrect path for copying build artifacts
  modules/front-end/Dockerfile
Labels: bug, angular
