Repository featbit/featbit, pull requests merged in 2025-03, with the labels that each got.

#713 🐛 fix: da server pg connection error
  modules/data-analytics/Dockerfile
  modules/data-analytics/app/setting.py
Labels: da-server

#709 ✨ feat: restrict users from changing organization's default permissions
  infra/mongodb/docker-entrypoint-initdb.d/init.js
  infra/postgresql/docker-entrypoint-initdb.d/c_seed_data.sql
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.html
  modules/front-end/src/app/features/safe/workspaces/organization/organization.component.ts
  modules/front-end/src/app/shared/policy.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: ui

#715 🐛 fix: insights not write to database
  modules/back-end/src/Infrastructure/AppService/InsightsWriter.cs
  modules/back-end/src/Infrastructure/ConfigureServices.cs
  modules/back-end/src/Infrastructure/Messages/EndUserMessageHandler.cs
  modules/back-end/src/Infrastructure/Messages/InsightMessageHandler.cs
  modules/back-end/src/Infrastructure/Redis/RedisMessageConsumer.cs
  modules/back-end/src/Infrastructure/Services/EntityFrameworkCore/InsightService.cs
Labels: bug, api

#714 🐛 fix: totalCount should never be None
  modules/data-analytics/app/main/models/statistics/end_user/end_user_statistics.py
Labels: bug, da-server

#716 🚀 perf: refactor InsightsWriter
  docker/composes/docker-compose-infra.yml
  modules/back-end/src/Domain/Utils/ValueStopwatch.cs
  modules/back-end/src/Infrastructure/AppService/InsightsWriter.cs
  modules/back-end/src/Infrastructure/Services/EntityFrameworkCore/InsightService.cs
  modules/back-end/src/Infrastructure/Services/MongoDb/InsightService.cs
Labels: enhancement, api

#717 ✨ feat: configure logging level from env variables
  modules/back-end/README.md
  modules/back-end/src/Api/Program.cs
  modules/back-end/src/Api/Setup/ConfigureSerilog.cs
  modules/back-end/src/Api/Setup/HostBuilder.cs
  modules/back-end/src/Api/Setup/ServicesRegister.cs
  modules/back-end/src/Api/appsettings.Development.json
  modules/back-end/src/Api/appsettings.json
  modules/evaluation-server/README.md
  modules/evaluation-server/src/Api/Program.cs
  modules/evaluation-server/src/Api/Setup/ConfigureSerilog.cs
  modules/evaluation-server/src/Api/Setup/HostBuilder.cs
  modules/evaluation-server/src/Api/Setup/ServicesRegister.cs
  modules/evaluation-server/src/Api/appsettings.Development.json
  modules/evaluation-server/src/Api/appsettings.json
Labels: enhancement, api, evalution-server

#718 🐛 fix: new property not copied to target environment
  modules/back-end/src/Application/FeatureFlags/CopyToEnv.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheck.cs
  modules/back-end/src/Application/FeatureFlags/CopyToEnvPrecheckResult.cs
  modules/back-end/src/Application/Services/IEndUserService.cs
  modules/back-end/src/Infrastructure/Services/EntityFrameworkCore/EndUserService.cs
  modules/back-end/src/Infrastructure/Services/MongoDb/EndUserService.cs
  modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.less
  modules/front-end/src/app/core/components/copy-feature-flag-modal/copy-feature-flag-modal.component.ts
  modules/front-end/src/app/core/components/props-drawer/props-drawer.component.html
  modules/front-end/src/app/features/safe/feature-flags/types/feature-flag.ts
  modules/front-end/src/locale/messages.xlf
  modules/front-end/src/locale/messages.zh.xlf
Labels: bug, api
